# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_methods.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_methods.ipynb 3
from fastcore.basics import patch
from .core import App

# %% ../nbs/02_methods.ipynb 4
@patch
def insert_text(app:App, text:str):
    '''`text를 입력합니다.'''
    action = app.actions.InsertText
    p = action.pset
    p.Text = text
    return action.run()
