# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_api/04_constants.ipynb.

# %% auto 0
__all__ = ['char_fields', 'para_fields', 'korean_fonts', 'english_fonts', 'chinese_fonts', 'japanese_fonts', 'other_fonts',
           'symbol_fonts', 'user_fonts', 'MaskOption', 'ScanStartPosition', 'ScanEndPosition', 'ScanDirection',
           'MoveId', 'SizeOption', 'Effect', 'SelectionOption', 'Direction', 'Thickness']

# %% ../nbs/02_api/04_constants.ipynb 3
from enum import Enum, auto


# %% ../nbs/02_api/04_constants.ipynb 4
# constants
char_fields = [
    "Bold",
    "DiacSymMark",
    "Emboss",
    "Engrave",
    "FaceNameHangul",
    "FaceNameHanja",
    "FaceNameJapanese",
    "FaceNameLatin",
    "FaceNameOther",
    "FaceNameSymbol",
    "FaceNameUser",
    "FontTypeHangul",
    "FontTypeHanja",
    "FontTypeJapanese",
    "FontTypeLatin",
    "FontTypeOther",
    "FontTypeSymbol",
    "FontTypeUser",
    "Height",
    "Italic",
    "OffsetHangul",
    "OffsetHanja",
    "OffsetJapanese",
    "OffsetLatin",
    "OffsetOther",
    "OffsetSymbol",
    "OffsetUser",
    "OutLineType",
    "RatioHangul",
    "RatioHanja",
    "RatioJapanese",
    "RatioLatin",
    "RatioOther",
    "RatioSymbol",
    "RatioUser",
    "ShadeColor",
    "ShadowColor",
    "ShadowOffsetX",
    "ShadowOffsetY",
    "ShadowType",
    "SizeHangul",
    "SizeHanja",
    "SizeJapanese",
    "SizeLatin",
    "SizeOther",
    "SizeSymbol",
    "SizeUser",
    "SmallCaps",
    "SpacingHangul",
    "SpacingHanja",
    "SpacingJapanese",
    "SpacingLatin",
    "SpacingOther",
    "SpacingSymbol",
    "SpacingUser",
    "StrikeOutColor",
    "StrikeOutShape",
    "StrikeOutType",
    "SubScript",
    "SuperScript",
    "TextColor",
    "UnderlineColor",
    "UnderlineShape",
    "UnderlineType",
    "UseFontSpace",
    "UseKerning",
]

para_fields = [
    "AlignType",
    "AutoSpaceEAsianEng",
    "AutoSpaceEAsianNum",
    "BorderConnect",
    "BorderOffsetBottom",
    "BorderOffsetLeft",
    "BorderOffsetRight",
    "BorderOffsetTop",
    "BorderText",
    "BreakLatinWord",
    "BreakNonLatinWord",
    "Checked",
    "Condense",
    "FontLineHeight",
    "HeadingType",
    "Indentation",
    "KeepLinesTogether",
    "KeepWithNext",
    "LeftMargin",
    "Level",
    "LineSpacing",
    "LineSpacingType",
    "LineWrap",
    "NextSpacing",
    "PagebreakBefore",
    "PrevSpacing",
    "RightMargin",
    "SnapToGrid",
    "SuppressLineNum",
    "TailType",
    "TextAlignment",
    "WidowOrphan",
]

# %% ../nbs/02_api/04_constants.ipynb 5
korean_fonts = [
    "명조",
    "고딕",
    "샘물",
    "필기",
    "시스템",
    "옛한글",
    "가는공한",
    "중간공한",
    "굵은공한",
    "가는한",
    "중간한",
    "굵은한",
    "펜흘림",
    "복숭아",
    "옥수수",
    "오이",
    "가지",
    "강낭콩",
    "딸기",
    "타이프",
    "HY 둥근고딕",
    "한양신명조",
    "한양견명조",
    "한양중고딕",
    "한양견고딕",
    "한양그래픽",
    "한양궁서",
    "휴먼명조",
    "휴먼고딕",
    "가는안상수체",
    "중간안상수체",
    "굵은안상수체",
    "휴먼가는샘체",
    "휴먼중간샘체",
    "휴먼굵은샘체",
    "휴먼가는팸체",
    "휴먼중간팸체",
    "휴먼굵은팸체",
    "휴먼옛체",
    "문화바탕",
    "문화바탕제목",
    "문화돋움",
    "문화돋움제목",
    "문화쓰기",
    "문화쓰기흘림",
    "태 나무",
    "태 헤드라인 D",
    "태 가는 헤드라인 D",
    "태 헤드라인 T",
    "태 가는 헤드라인 T",
    "양재 다운명조 M",
    "양재 본목각 M",
    "양재 소슬",
    "양재 튼튼 B",
    "양재 둘기",
    "양재 참숯 B",
    "양재 매화",
    "양재 샤넬",
    "양재 와당",
    "양재 이니셜",
    "신명 세명조",
    "신명 신명조",
    "신명 신신명조",
    "신명 중명조",
    "신명 태명조",
    "신명 견명조",
    "신명 신문명조",
    "신명 순명조",
    "신명 세고딕",
    "신명 중고딕",
    "신명 태고딕",
    "신명 견고딕",
    "신명 세나루",
    "신명 디나루",
    "신명 신그래픽",
    "신명 태그래픽",
    "신명 궁서",
    "#세명조",
    "#신명조",
    "#중명조",
    "#신중명조",
    "#화명조 A",
    "#화명조 B",
    "#태명조",
    "#신태명조",
    "#태신명조",
    "#견명조",
    "#신문명조",
    "#신문태명",
    "#신문견명",
    "#세고딕",
    "#신세고딕",
    "#중고딕",
    "#태고딕",
    "#견고딕",
    "#신문고딕",
    "#신문태고",
    "#신문견고",
    "#세나루",
    "#신세나루",
    "#디나루",
    "#신디나루",
    "#그래픽",
    "#신그래픽",
    "#태그래픽",
    "#궁서",
    "#공작",
    "#수암 A",
    "#수암 B",
    "#빅",
]

# %% ../nbs/02_api/04_constants.ipynb 6
english_fonts = [
    "명조",
    "고딕",
    "산세리프",
    "필기",
    "시스템",
    "가는공한",
    "중간공한",
    "굵은공한",
    "가는한",
    "중간한",
    "굵은한",
    "펜흘림",
    "옥수수",
    "오이",
    "타이프",
    "수식",
    "HY 둥근고딕",
    "한양신명조",
    "한양견명조",
    "한양중고딕",
    "한양견고딕",
    "한양그래픽",
    "한양궁서",
    "HCI Tulip",
    "HCI Hollyhock",
    "HCI Columbine",
    "HCI Acacia",
    "HCI Bellflower",
    "HCI Hollyhock Narrow",
    "HCI Morning Glory",
    "HCI Poppy",
    "HCI Centaurea",
    "가는안상수체영문",
    "중간안상수체영문",
    "굵은안상수체영문",
    "태 나무",
    "양재 다운명조 M",
    "양재 본목각 M",
    "양재 소슬",
    "양재 튼튼 B",
    "양재 둘기",
    "양재 참숯 B",
    "양재 매화",
    "양재 샤넬",
    "양재 와당",
    "양재 이니셜",
    "신명 세명조",
    "신명 신명조",
    "신명 신신명조",
    "신명 중명조",
    "신명 태명조",
    "신명 견명조",
    "신명 신문명조",
    "신명 순명조",
    "신명 세고딕",
    "신명 중고딕",
    "신명 태고딕",
    "신명 견고딕",
    "신명 신문고딕",
    "신명 세나루",
    "신명 디나루",
    "신명 신그래픽",
    "신명 태그래픽",
    "신명 궁서",
    "#세명조",
    "#신명조",
    "#중명조",
    "#신중명조",
    "#화명조 A",
    "#화명조 B",
    "#태명조",
    "#신태명조",
    "#태신명조",
    "#견명조",
    "#신문명조",
    "#신문태명",
    "#신문견명",
    "#세고딕",
    "#신세고딕",
    "#중고딕",
    "#태고딕",
    "#견고딕",
    "#신문고딕",
    "#신문태고",
    "#신문견고",
    "#세나루",
    "#신세나루",
    "#디나루",
    "#신디나루",
    "#그래픽",
    "#신그래픽",
    "#태그래픽",
    "#궁서",
    "#필기",
    "#공작",
    "#수암 A",
    "#수암 B",
    "#헤드라인 A",
    "#헤드라인 B",
    "#빅",
    "AmeriGarmnd BT",
    "Baskerville BT",
    "Bodoni Bd BT",
    "Bodoni Bk BT",
    "CentSchbook BT",
    "Courier10 BT",
    "Courier10 BT",
    "GoudyOlSt BT",
    "OCR-A BT",
    "OCR-B-10 BT",
    "Orator10 BT",
    "Swis721 BT",
    "BernhardFashion BT",
    "Blippo Blk BT",
    "BroadwayEngraved BT",
    "BrushScript BT",
    "Cooper Blk BT",
    "CommercialScript BT",
    "DomCasual BT",
    "Freehand591 BT",
    "FuturaBlack BT",
    "Hobo BT",
    "Liberty BT",
    "MurrayHill Bd BT",
    "Newtext Bk BT",
    "Orbit-B BT",
    "ParkAvenue BT",
    "Stencil BT",
]

# %% ../nbs/02_api/04_constants.ipynb 7
chinese_fonts = [
    "명조",
    "시스템",
    "시스템 약자",
    "시스템 간자",
    "신명조 약자",
    "신명조 간자",
    "중고딕 약자",
    "중고딕 간자",
    "해서 약자",
    "해서 간자",
    "한양신명조",
    "한양중고딕",
    "신명 세명조",
    "신명 중명조",
    "신명 태명조",
    "신명 견명조",
    "신명 신문명조",
    "신명 세고딕",
    "신명 중고딕",
    "신명 태고딕",
    "신명 견고딕",
    "신명 궁서",
    "#신명조",
    "#중명조",
    "#태명조",
    "#견명조",
    "#신문명조",
    "#신문견명",
    "#신세고딕",
    "#중고딕",
    "#태고딕",
    "#견고딕",
    "#신문고딕",
    "#신문견고",
    "#신세나루",
    "#신디나루",
    "#궁서",
]

# %% ../nbs/02_api/04_constants.ipynb 8
japanese_fonts = [
    "명조",
    "고딕",
    "시스템",
    "HY 둥근고딕",
    "한양신명조",
    "한양중고딕",
    "신명 신명조",
    "신명 태명조",
    "신명 견명조",
    "신명 중고딕",
    "신명 태고딕",
    "#세명조",
    "#태명조",
    "#세고딕",
    "#중고딕",
    "#태고딕",
    "한양신명조 V",
    "한양중고딕 V",
    "신명 신명조 V",
    "신명 태명조 V",
    "신명 견명조 V",
    "신명 중고딕 V",
    "신명 태고딕 V",
    "#세명조 V",
    "#태명조 V",
    "#세고딕 V",
    "#중고딕 V",
    "#태고딕 V",
]

# %% ../nbs/02_api/04_constants.ipynb 9
other_fonts = ["명조", "수식", "한양신명조"]

# %% ../nbs/02_api/04_constants.ipynb 10
symbol_fonts = [
    "명조",
    "시스템",
    "수식",
    "HY 둥근고딕",
    "한양신명조",
    "한양중고딕",
    "신명 견명조",
    "신명 견고딕",
    "신명 태그래픽",
    "#세명조",
    "#신명조",
    "#중명조",
    "#태명조",
    "#신태명조",
    "#태신명조",
    "#견명조",
    "#신문명조",
    "#세고딕",
    "#신세고딕",
    "#중고딕",
    "#태고딕",
    "#견고딕",
    "#신문고딕",
    "#세나루",
    "#신세나루",
    "#디나루",
    "#신디나루",
    "#그래픽",
    "#신그래픽",
    "#태그래픽",
    "#궁서",
    "#필기",
    "#공작",
    "#수암 A",
    "#빅",
]

# %% ../nbs/02_api/04_constants.ipynb 11
user_fonts = ["명조", "한글 풀어쓰기"]

# %% ../nbs/02_api/04_constants.ipynb 12
class MaskOption(Enum):
    Normal = 0x00
    Char = 0x01
    Inline = 0x02
    Ctrl = 0x04
    All = auto()

class ScanStartPosition(Enum):
    Current = 0x0000
    Specified = 0x0010
    Line = 0x0020
    Paragraph = 0x0030
    Section = 0x0040
    List = 0x0050
    Control = 0x0060
    Document = 0x0070

class ScanEndPosition(Enum):
    Current = 0x0000
    Specified = 0x0001
    Line = 0x0002
    Paragraph = 0x0003
    Section = 0x0004
    List = 0x0005
    Control = 0x0006
    Document = 0x0007

class ScanDirection(Enum):
    Forward = 0x0000
    Backward = 0x0100

# %% ../nbs/02_api/04_constants.ipynb 13
class MoveId(Enum):
    Main = 0
    CurList = 1
    TopOfFile = 2
    BottomOfFile = 3
    TopOfList = 4
    BottomOfList = 5
    StartOfPara = 6
    EndOfPara = 7
    StartOfWord = 8
    EndOfWord = 9
    NextPara = 10
    PrevPara = 11
    NextPos = 12
    PrevPos = 13
    NextPosEx = 14
    PrevPosEx = 15
    NextChar = 16
    PrevChar = 17
    NextWord = 18
    PrevWord = 19
    NextLine = 20
    PrevLine = 21
    StartOfLine = 22
    EndOfLine = 23
    ParentList = 24
    TopLevelList = 25
    RootList = 26
    CurrentCaret = 27
    LeftOfCell = 100
    RightOfCell = 101
    UpOfCell = 102
    DownOfCell = 103
    StartOfCell = 104
    EndOfCell = 105
    TopOfCell = 106
    BottomOfCell = 107
    ScrPos = 200
    ScanPos = 201


# %% ../nbs/02_api/04_constants.ipynb 14
class SizeOption(Enum):
    RealSize = 0
    SpecificSize = 1
    CellSize = 2
    CellSizeWithSameRatio = 3

class Effect(Enum):
    RealPicture = 0
    GrayScale = 1
    BlackWhite = 2

# %% ../nbs/02_api/04_constants.ipynb 15
class SelectionOption(Enum):
    Doc = ("MoveDocBegin", "MoveSelDocEnd")
    Para = ("MoveParaBegin", "MoveSelParaEnd")
    Line = ("MoveLineBegin", "MoveSelLineEnd")
    Word = ("MoveWordBegin", "MoveSelWordEnd")

# %% ../nbs/02_api/04_constants.ipynb 16
class ScanStartPosition(Enum):
    Current = 0x0000
    Specified = 0x0010
    Line = 0x0020
    Paragraph = 0x0030
    Section = 0x0040
    List = 0x0050
    Control = 0x0060
    Document = 0x0070

class ScanEndPosition(Enum):
    Current = 0x0000
    Specified = 0x0001
    Line = 0x0002
    Paragraph = 0x0003
    Section = 0x0004
    List = 0x0005
    Control = 0x0006
    Document = 0x0007

# %% ../nbs/02_api/04_constants.ipynb 17
class Direction(Enum):
    Forward = 0
    Backward = 1
    All = 2


# %% ../nbs/02_api/04_constants.ipynb 18
class Thickness(Enum):
    NULL = None
    최소값 = -1  # "최소값 (=0.1 mm)"
    _0_1_mm = 0  # "0.1 mm"
    _0_12_mm = 1  # "0.12 mm"
    _0_15_mm = 2  # "0.15 mm"
    _0_2_mm = 3  # "0.2 mm"
    _0_25_mm = 4  # "0.25 mm"
    _0_3_mm = 5  # "0.3 mm"
    _0_4_mm = 6  # "0.4 mm"
    _0_5_mm = 7  # "0.5 mm"
    _0_6_mm = 8  # "0.6 mm"
    _0_7_mm = 9  # "0.7 mm"
    _1_0_mm = 10  # "1.0 mm"
    _1_5_mm = 11  # "1.5 mm"
    _2_0_mm = 12  # "2.0 mm"
    _3_0_mm = 13  # "3.0 mm"
    _4_0_mm = 14  # "4.0 mm"
    _5_0_mm = 15  # "5.0 mm"
    최대값 = 16  # "최대값 (=5.0 mm)"
    
    @classmethod
    def get_thickness_description(cls, value):
        """
        Returns the description of the thickness based on the value.

        Parameters
        ----------
        value : int
            The value representing the thickness.

        Returns
        -------
        str
            The string description associated with the thickness value.
        """
        for thickness in cls:
            if thickness.value == value:
                return thickness.name.replace('_', '.')
        return None
