# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_api/02_parameters.ipynb.

# %% auto 0
__all__ = ['ParameterSet', 'FindReplace', 'CharShape', 'DrawFillAttr', 'TabDef', 'NumberingShape', 'BulletShape', 'DrawImageAttr',
           'ParaShape']

# %% ../nbs/02_api/02_parameters.ipynb 17
class ParameterSet:

    def __init__(self, parameterset):
        self._pset = parameterset

    @property
    def set(self):
        return self._pset


# %% ../nbs/02_api/02_parameters.ipynb 18
class FindReplace(ParameterSet):
    """
    ### FindReplace

56\) FindReplace : 찾기/찾아 바꾸기

| Item ID | Type | SubType | Description |
| --- | --- | --- | --- |
| FindString | PIT\_BSTR |  | 찾을 문자열 |
| ReplaceString | PIT\_BSTR |  | 바꿀 문자열 |
| Direction | PIT\_UI1 |  | 찾을 방향 :0 \= 아래쪽, 1 \= 위쪽, 2 \= 문서 전체 |
| MatchCase | PIT\_UI1 |  | 대소문자 구별 (on / off) |
| AllWordForms | PIT\_UI1 |  | 문자열 결합 (on / off) |
| SeveralWords | PIT\_UI1 |  | 여러 단어 찾기 (on / off) |
| UseWildCards | PIT\_UI1 |  | 아무개 문자 (on / off) |
| WholeWordOnly | PIT\_UI1 |  | 온전한 낱말 (on / off) |
| AutoSpell | PIT\_UI1 |  | 토씨 자동 교정 (on / off) |
| ReplaceMode | PIT\_UI1 |  | 찾아 바꾸기 모드 (on / off) |
| IgnoreFindString | PIT\_UI1 |  | 찾을 문자열 무시 (on / off) |
| IgnoreReplaceString | PIT\_UI1 |  | 바꿀 문자열 무시 (on / off) |
| FindCharShape | PIT\_SET | CharShape | 찾을 글자 모양 |
| FindParaShape | PIT\_SET | ParaShape | 찾을 문단 모양 |
| ReplaceCharShape | PIT\_SET | CharShape | 바꿀 글자 모양 |
| ReplaceParaShape | PIT\_SET | ParaShape | 바꿀 문단 모양 |
| FindStyle | PIT\_BSTR |  | 찾을 스타일 |
| ReplaceStyle | PIT\_BSTR |  | 바꿀 스타일 |
| IgnoreMessage | PIT\_UI1 |  | 메시지박스 표시 안함. (on / off) |
| HanjaFromHangul | PIT\_UI1 |  | 한글임으로 한자 차기 |
| FindJaso | PIT\_UI1 |  | 자소로 찾기 (on / off) |
| FindRegExp | PIT\_UI1 |  | 정규식(조건식)으로 찾기 (on / off) (ver:0x06050107\) |
| FindType | PIT\_UI1 |  | 다시 찾기를 할 때 마지막으로 실행한 \[찾기 TRUE]를 할 것인가 \[찾아가기 FALSE]할 것인가의 여부 (ver:0x06050110\) |

 



    """

    @property
    def find_string(self):
        """찾을 문자열"""
        return self._pset.Item("FindString")

    @find_string.setter
    def find_string(self, value):
        if value is None:
            return self._pset.RemoveItem("FindString")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FindString", value)

    @property
    def replace_string(self):
        """바꿀 문자열"""
        return self._pset.Item("ReplaceString")

    @replace_string.setter
    def replace_string(self, value):
        if value is None:
            return self._pset.RemoveItem("ReplaceString")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("ReplaceString", value)

    @property
    def direction(self):
        """
        찾을 방향 :
        0 = 아래쪽, 1 = 위쪽, 2 = 문서 전체
        """
        return self._pset.Item("Direction")

    @direction.setter
    def direction(self, value):
        if value is None:
            return self._pset.RemoveItem("Direction")
        assert value in [0, 1, 2], "값은 0=아래쪽, 1=위쪽, 2=문서 전체 중 하나여야 합니다."
        return self._pset.SetItem("Direction", value)

    @property
    def match_case(self):
        """대소문자 구분 (on/off)"""
        return self._pset.Item("MatchCase")

    @match_case.setter
    def match_case(self, value):
        if value is None:
            return self._pset.RemoveItem("MatchCase")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("MatchCase", value)

    @property
    def all_word_forms(self):
        """모든 단어 형태 (on/off)"""
        return self._pset.Item("AllWordForms")

    @all_word_forms.setter
    def all_word_forms(self, value):
        if value is None:
            return self._pset.RemoveItem("AllWordForms")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("AllWordForms", value)

    @property
    def several_words(self):
        """여러 단어 찾기 (on/off)"""
        return self._pset.Item("SeveralWords")

    @several_words.setter
    def several_words(self, value):
        if value is None:
            return self._pset.RemoveItem("SeveralWords")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("SeveralWords", value)

    @property
    def use_wildcards(self):
        """와일드카드 사용 (on/off)"""
        return self._pset.Item("UseWildCards")

    @use_wildcards.setter
    def use_wildcards(self, value):
        if value is None:
            return self._pset.RemoveItem("UseWildCards")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("UseWildCards", value)

    @property
    def whole_word_only(self):
        """전체 단어만 찾기 (on/off)"""
        return self._pset.Item("WholeWordOnly")

    @whole_word_only.setter
    def whole_word_only(self, value):
        if value is None:
            return self._pset.RemoveItem("WholeWordOnly")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("WholeWordOnly", value)

    @property
    def auto_spell(self):
        """자동 맞춤법 사용 (on/off)"""
        return self._pset.Item("AutoSpell")

    @auto_spell.setter
    def auto_spell(self, value):
        if value is None:
            return self._pset.RemoveItem("AutoSpell")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("AutoSpell", value)

    @property
    def replace_mode(self):
        """바꾸기 모드 (on/off)"""
        return self._pset.Item("ReplaceMode")

    @replace_mode.setter
    def replace_mode(self, value):
        if value is None:
            return self._pset.RemoveItem("ReplaceMode")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("ReplaceMode", value)

    @property
    def ignore_find_string(self):
        """찾을 문자열 무시 (on/off)"""
        return self._pset.Item("IgnoreFindString")

    @ignore_find_string.setter
    def ignore_find_string(self, value):
        if value is None:
            return self._pset.RemoveItem("IgnoreFindString")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("IgnoreFindString", value)

    @property
    def ignore_replace_string(self):
        """바꿀 문자열 무시 (on/off)"""
        return self._pset.Item("IgnoreReplaceString")

    @ignore_replace_string.setter
    def ignore_replace_string(self, value):
        if value is None:
            return self._pset.RemoveItem("IgnoreReplaceString")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("IgnoreReplaceString", value)

    @property
    def find_charshape(self):
        """찾을 글자 모양"""
        return self._pset.Item("FindCharShape")

    @find_charshape.setter
    def find_charshape(self, value):
        if value is None:
            return self._pset.RemoveItem("FindCharShape")
        assert isinstance(value, CharShape), "값은 CharShape 객체여야 합니다."
        return self._pset.SetItem("FindCharShape", value)

    @property
    def find_parashape(self):
        """찾을 문단 모양"""
        return self._pset.Item("FindParaShape")

    @find_parashape.setter
    def find_parashape(self, value):
        if value is None:
            return self._pset.RemoveItem("FindParaShape")
        assert isinstance(value, ParaShape), "값은 ParaShape 객체여야 합니다."
        return self._pset.SetItem("FindParaShape", value)

    @property
    def replace_charshape(self):
        """바꿀 글자 모양"""
        return self._pset.Item("ReplaceCharShape")

    @replace_charshape.setter
    def replace_charshape(self, value):
        if value is None:
            return self._pset.RemoveItem("ReplaceCharShape")
        assert isinstance(value, CharShape), "값은 CharShape 객체여야 합니다."
        return self._pset.SetItem("ReplaceCharShape", value)

    @property
    def replace_parashape(self):
        """바꿀 문단 모양"""
        return self._pset.Item("ReplaceParaShape")

    @replace_parashape.setter
    def replace_parashape(self, value):
        if value is None:
            return self._pset.RemoveItem("ReplaceParaShape")
        assert isinstance(value, ParaShape), "값은 ParaShape 객체여야 합니다."
        return self._pset.SetItem("ReplaceParaShape", value)

    @property
    def find_style(self):
        """찾을 스타일"""
        return self._pset.Item("FindStyle")

    @find_style.setter
    def find_style(self, value):
        if value is None:
            return self._pset.RemoveItem("FindStyle")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FindStyle", value)

    @property
    def replace_style(self):
        """바꿀 스타일"""
        return self._pset.Item("ReplaceStyle")

    @replace_style.setter
    def replace_style(self, value):
        if value is None:
            return self._pset.RemoveItem("ReplaceStyle")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("ReplaceStyle", value)

    @property
    def ignore_message(self):
        """메시지 무시 (on/off)"""
        return self._pset.Item("IgnoreMessage")

    @ignore_message.setter
    def ignore_message(self, value):
        if value is None:
            return self._pset.RemoveItem("IgnoreMessage")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("IgnoreMessage", value)

    @property
    def hanja_from_hangul(self):
        """한글에서 한자 변환"""
        return self._pset.Item("HanjaFromHangul")

    @hanja_from_hangul.setter
    def hanja_from_hangul(self, value):
        if value is None:
            return self._pset.RemoveItem("HanjaFromHangul")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("HanjaFromHangul", value)

    @property
    def find_jaso(self):
        """자소로 찾기 (on/off)"""
        return self._pset.Item("FindJaso")

    @find_jaso.setter
    def find_jaso(self, value):
        if value is None:
            return self._pset.RemoveItem("FindJaso")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("FindJaso", value)

    @property
    def find_regexp(self):
        """정규식 찾기 (on/off)"""
        return self._pset.Item("FindRegExp")

    @find_regexp.setter
    def find_regexp(self, value):
        if value is None:
            return self._pset.RemoveItem("FindRegExp")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("FindRegExp", value)

    @property
    def find_type(self):
        """찾기 유형"""
        return self._pset.Item("FindType")

    @find_type.setter
    def find_type(self, value):
        if value is None:
            return self._pset.RemoveItem("FindType")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("FindType", value)


# %% ../nbs/02_api/02_parameters.ipynb 19
class CharShape(ParameterSet):
    """
  ### CharShape

13\) CharShape : 글자 모양

| Item ID | Type | SubType | Description |
| --- | --- | --- | --- |
| FaceNameHangul | PIT\_BSTR |  | 글꼴 이름 (한글) |
| FaceNameLatin | PIT\_BSTR |  | 글꼴 이름 (영문) |
| FaceNameHanja | PIT\_BSTR |  | 글꼴 이름 (한자) |
| FaceNameJapanese | PIT\_BSTR |  | 글꼴 이름 (일본어) |
| FaceNameOther | PIT\_BSTR |  | 글꼴 이름 (기타) |
| FaceNameSymbol | PIT\_BSTR |  | 글꼴 이름 (심벌) |
| FaceNameUser | PIT\_BSTR |  | 글꼴 이름 (사용자) |
| FontTypeHangul | PIT\_UI1 |  | 폰트 종류 (한글) : 0 \= don't care, 1 \= TTF, 2 \= HFT |
| FontTypeLatin | PIT\_UI1 |  | 폰트 종류 (영문) : 0 \= don't care, 1 \= TTF, 2 \= HFT |
| FontTypeHanja | PIT\_UI1 |  | 폰트 종류 (한자) : 0 \= don't care, 1 \= TTF, 2 \= HFT |
| FontTypeJapanese | PIT\_UI1 |  | 폰트 종류 (일본어) : 0 \= don't care, 1 \= TTF, 2 \= HFT |
| FontTypeOther | PIT\_UI1 |  | 폰트 종류 (기타) : 0 \= don't care, 1 \= TTF, 2 \= HFT |
| FontTypeSymbol | PIT\_UI1 |  | 폰트 종류 (심벌) : 0 \= don't care, 1 \= TTF, 2 \= HFT |
| FontTypeUser | PIT\_UI1 |  | 폰트 종류 (사용자) : 0 \= don't care, 1 \= TTF, 2 \= HFT |
| SizeHangul | PIT\_UI1 |  | 각 언어별 크기 비율. (한글) 10% \- 250% |
| SizeLatin | PIT\_UI1 |  | 각 언어별 크기 비율. (영문) 10% \- 250% |
| SizeHanja | PIT\_UI1 |  | 각 언어별 크기 비율. (한자) 10% \- 250% |
| SizeJapanese | PIT\_UI1 |  | 각 언어별 크기 비율. (일본어) 10% \- 250% |
| SizeOther | PIT\_UI1 |  | 각 언어별 크기 비율. (기타) 10% \- 250% |
| SizeSymbol | PIT\_UI1 |  | 각 언어별 크기 비율. (심벌) 10% \- 250% |
| SizeUser | PIT\_UI1 |  | 각 언어별 크기 비율. (사용자) 10% \- 250% |
| RatioHangul | PIT\_UI1 |  | 각 언어별 장평 비율. (한글) 50% \- 200% |
| RatioLatin | PIT\_UI1 |  | 각 언어별 장평 비율. (영문) 50% \- 200% |
| RatioHanja | PIT\_UI1 |  | 각 언어별 장평 비율. (한자) 50% \- 200% |
| RatioJapanese | PIT\_UI1 |  | 각 언어별 장평 비율. (일본어) 50% \- 200% |
| RatioOther | PIT\_UI1 |  | 각 언어별 장평 비율. (기타) 50% \- 200% |
| RatioSymbol | PIT\_UI1 |  | 각 언어별 장평 비율. (심벌) 50% \- 200% |
| RatioUser | PIT\_UI1 |  | 각 언어별 장평 비율. (사용자) 50% \- 200% |
| SpacingHangul | PIT\_I1 |  | 각 언어별 자간. (한글) \-50% \- 50% |
| SpacingLatin | PIT\_I1 |  | 각 언어별 자간. (영문) \-50% \- 50% |
| SpacingHanja | PIT\_I1 |  | 각 언어별 자간. (한자) \-50% \- 50% |
| SpacingJapanese | PIT\_I1 |  | 각 언어별 자간. (일본어) \-50% \- 50% |
| SpacingOther | PIT\_I1 |  | 각 언어별 자간. (기타) \-50% \- 50% |
| SpacingSymbol | PIT\_I1 |  | 각 언어별 자간. (심벌) \-50% \- 50% |
| SpacingUser | PIT\_I1 |  | 각 언어별 자간. (사용자) \-50% \- 50% |
| OffsetHangul | PIT\_I1 |  | 각 언어별 오프셋. (한글) \-100% \- 100% |
| OffsetLatin | PIT\_I1 |  | 각 언어별 오프셋. (영문) \-100% \- 100% |
| OffsetHanja | PIT\_I1 |  | 각 언어별 오프셋. (한자) \-100% \- 100% |
| OffsetJapanese | PIT\_I1 |  | 각 언어별 오프셋. (일본어) \-100% \- 100% |
| OffsetOther | PIT\_I1 |  | 각 언어별 오프셋. (기타) \-100% \- 100% |
| OffsetSymbol | PIT\_I1 |  | 각 언어별 오프셋. (심벌) \-100% \- 100% |
| OffsetUser | PIT\_I1 |  | 각 언어별 오프셋. (사용자) \-100% \- 100% |
| Bold | PIT\_UI1 |  | Bold : 0 \= off, 1 \= on |
| Italic | PIT\_UI1 |  | Italic : 0 \= off, 1 \= on |
| SmallCaps | PIT\_UI1 |  | Small Caps : 0 \= off, 1 \= on |
| Emboss | PIT\_UI1 |  | Emboss : 0 \= off, 1 \= on |
| Engrave | PIT\_UI1 |  | Engrave : 0 \= off, 1 \= on |
| SuperScript | PIT\_UI1 |  | Superscript : 0 \= off, 1 \= on |
| SubScript | PIT\_UI1 |  | Subscript : 0 \= off, 1 \= on |
| UnderlineType | PIT\_UI1 |  | 밑줄 종류 :  0 \= none, 1 \= bottom, 2 \= center, 3 \= top |
| OutlineType | PIT\_UI1 |  | 외곽선 종류 : 0 \= none, 1 \= solid, 2 \= dot, 3 \= thick,  4 \= dash, 5 \= dashdot, 6 \= dashdotdot |
| ShadowType | PIT\_UI1 |  | 그림자 종류 : 0 \= none, 1 \= drop, 2 \= continuous |
| TextColor | PIT\_UI4 |  | 글자색. (COLORREF)RGB color를 나타내기 위한 32비트 값 (0x00BBGGRR) |
| ShadeColor | PIT\_UI4 |  | 음영색. (COLORREF)RGB color를 나타내기 위한 32비트 값 (0x00BBGGRR) |
| UnderlineShape | PIT\_UI1 |  | 밑줄 모양 : 선 종류 |
| UnderlineColor | PIT\_UI4 |  | 밑줄 색 (COLORREF)RGB color를 나타내기 위한 32비트 값 (0x00BBGGRR) |
| ShadowOffsetX | PIT\_I1 |  | 그림자 간격 (X 방향) \-100% \- 100% |
| ShadowOffsetY | PIT\_I1 |  | 그림자 간격 (Y 방향) \-100% \- 100% |
| ShadowColor | PIT\_UI4 |  | 그림자 색 (COLORREF)RGB color를 나타내기 위한 32비트 값 (0x00BBGGRR) |
| StrikeOutType | PIT\_UI1 |  | 취소선 종류 : 0 \= none, 1 \= red single, 2 \= red double,  3 \= text single, 4 \= text double |
| DiacSymMark | PIT\_UI1 |  | 강조점 종류 : 0 \= none, 1 \= 검정 동그라미, 2 \= 속 빈 동그라미 |
| UseFontSpace | PIT\_UI1 |  | 글꼴에 어울리는 빈칸 : 0 \= off, 1 \= on |
| UseKerning | PIT\_UI1 |  | 커닝 : 0 \= off, 1 \= on |
| Height | PIT\_I4 |  | 글자 크기 (HWPUNIT) |
| BorderFill | PIT\_SET | BorderFill | 테두리/배경 (한글2007에 새로 추가) |

    """


    @property
    def facename_hangul(self):
        """폰트 이름 (한글)"""
        return self._pset.Item("FaceNameHangul")

    @facename_hangul.setter
    def facename_hangul(self, value):
        if value is None:
            return self._pset.RemoveItem("FaceNameHangul")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FaceNameHangul", value)

    @property
    def facename_latin(self):
        """폰트 이름 (영문)"""
        return self._pset.Item("FaceNameLatin")

    @facename_latin.setter
    def facename_latin(self, value):
        if value is None:
            return self._pset.RemoveItem("FaceNameLatin")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FaceNameLatin", value)

    @property
    def facename_hanja(self):
        """폰트 이름 (한자)"""
        return self._pset.Item("FaceNameHanja")

    @facename_hanja.setter
    def facename_hanja(self, value):
        if value is None:
            return self._pset.RemoveItem("FaceNameHanja")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FaceNameHanja", value)

    @property
    def facename_japanese(self):
        """폰트 이름 (일본어)"""
        return self._pset.Item("FaceNameJapanese")

    @facename_japanese.setter
    def facename_japanese(self, value):
        if value is None:
            return self._pset.RemoveItem("FaceNameJapanese")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FaceNameJapanese", value)

    @property
    def facename_other(self):
        """폰트 이름 (기타)"""
        return self._pset.Item("FaceNameOther")

    @facename_other.setter
    def facename_other(self, value):
        if value is None:
            return self._pset.RemoveItem("FaceNameOther")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FaceNameOther", value)

    @property
    def facename_symbol(self):
        """폰트 이름 (기호)"""
        return self._pset.Item("FaceNameSymbol")

    @facename_symbol.setter
    def facename_symbol(self, value):
        if value is None:
            return self._pset.RemoveItem("FaceNameSymbol")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FaceNameSymbol", value)

    @property
    def facename_user(self):
        """폰트 이름 (사용자)"""
        return self._pset.Item("FaceNameUser")

    @facename_user.setter
    def facename_user(self, value):
        if value is None:
            return self._pset.RemoveItem("FaceNameUser")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FaceNameUser", value)

    @property
    def fonttype_hangul(self):
        """폰트 종류 (한글): 0 = don't care, 1 = TTF, 2 = HFT"""
        return self._pset.Item("FontTypeHangul")

    @fonttype_hangul.setter
    def fonttype_hangul(self, value):
        if value is None:
            return self._pset.RemoveItem("FontTypeHangul")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("FontTypeHangul", value)

    @property
    def fonttype_latin(self):
        """폰트 종류 (영문): 0 = don't care, 1 = TTF, 2 = HFT"""
        return self._pset.Item("FontTypeLatin")

    @fonttype_latin.setter
    def fonttype_latin(self, value):
        if value is None:
            return self._pset.RemoveItem("FontTypeLatin")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("FontTypeLatin", value)

    @property
    def fonttype_hanja(self):
        """폰트 종류 (한자): 0 = don't care, 1 = TTF, 2 = HFT"""
        return self._pset.Item("FontTypeHanja")

    @fonttype_hanja.setter
    def fonttype_hanja(self, value):
        if value is None:
            return self._pset.RemoveItem("FontTypeHanja")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("FontTypeHanja", value)

    @property
    def fonttype_japanese(self):
        """폰트 종류 (일본어): 0 = don't care, 1 = TTF, 2 = HFT"""
        return self._pset.Item("FontTypeJapanese")

    @fonttype_japanese.setter
    def fonttype_japanese(self, value):
        if value is None:
            return self._pset.RemoveItem("FontTypeJapanese")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("FontTypeJapanese", value)

    @property
    def fonttype_other(self):
        """폰트 종류 (기타): 0 = don't care, 1 = TTF, 2 = HFT"""
        return self._pset.Item("FontTypeOther")

    @fonttype_other.setter
    def fonttype_other(self, value):
        if value is None:
            return self._pset.RemoveItem("FontTypeOther")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("FontTypeOther", value)

    @property
    def fonttype_symbol(self):
        """폰트 종류 (기호): 0 = don't care, 1 = TTF, 2 = HFT"""
        return self._pset.Item("FontTypeSymbol")

    @fonttype_symbol.setter
    def fonttype_symbol(self, value):
        if value is None:
            return self._pset.RemoveItem("FontTypeSymbol")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("FontTypeSymbol", value)

    @property
    def fonttype_user(self):
        """폰트 종류 (사용자): 0 = don't care, 1 = TTF, 2 = HFT"""
        return self._pset.Item("FontTypeUser")

    @fonttype_user.setter
    def fonttype_user(self, value):
        if value is None:
            return self._pset.RemoveItem("FontTypeUser")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("FontTypeUser", value)

    @property
    def size_hangul(self):
        """크기 설정 비율 (한글): 10% - 250%"""
        return self._pset.Item("SizeHangul")

    @size_hangul.setter
    def size_hangul(self, value):
        if value is None:
            return self._pset.RemoveItem("SizeHangul")
        assert 10 <= value <= 250, "값은 10에서 250 사이여야 합니다."
        return self._pset.SetItem("SizeHangul", value)

    @property
    def size_latin(self):
        """크기 설정 비율 (영문): 10% - 250%"""
        return self._pset.Item("SizeLatin")

    @size_latin.setter
    def size_latin(self, value):
        if value is None:
            return self._pset.RemoveItem("SizeLatin")
        assert 10 <= value <= 250, "값은 10에서 250 사이여야 합니다."
        return self._pset.SetItem("SizeLatin", value)

    @property
    def size_hanja(self):
        """크기 설정 비율 (한자): 10% - 250%"""
        return self._pset.Item("SizeHanja")

    @size_hanja.setter
    def size_hanja(self, value):
        if value is None:
            return self._pset.RemoveItem("SizeHanja")
        assert 10 <= value <= 250, "값은 10에서 250 사이여야 합니다."
        return self._pset.SetItem("SizeHanja", value)

    @property
    def size_japanese(self):
        """크기 설정 비율 (일본어): 10% - 250%"""
        return self._pset.Item("SizeJapanese")

    @size_japanese.setter
    def size_japanese(self, value):
        if value is None:
            return self._pset.RemoveItem("SizeJapanese")
        assert 10 <= value <= 250, "값은 10에서 250 사이여야 합니다."
        return self._pset.SetItem("SizeJapanese", value)

    @property
    def size_other(self):
        """크기 설정 비율 (기타): 10% - 250%"""
        return self._pset.Item("SizeOther")

    @size_other.setter
    def size_other(self, value):
        if value is None:
            return self._pset.RemoveItem("SizeOther")
        assert 10 <= value <= 250, "값은 10에서 250 사이여야 합니다."
        return self._pset.SetItem("SizeOther", value)

    @property
    def size_symbol(self):
        """크기 설정 비율 (기호): 10% - 250%"""
        return self._pset.Item("SizeSymbol")

    @size_symbol.setter
    def size_symbol(self, value):
        if value is None:
            return self._pset.RemoveItem("SizeSymbol")
        assert 10 <= value <= 250, "값은 10에서 250 사이여야 합니다."
        return self._pset.SetItem("SizeSymbol", value)

    @property
    def size_user(self):
        """크기 설정 비율 (사용자): 10% - 250%"""
        return self._pset.Item("SizeUser")

    @size_user.setter
    def size_user(self, value):
        if value is None:
            return self._pset.RemoveItem("SizeUser")
        assert 10 <= value <= 250, "값은 10에서 250 사이여야 합니다."

    @property
    def ratio_hangul(self):
        """각 언어별 장평 비율 (한글): 50% - 200%"""
        return self._pset.Item("RatioHangul")

    @ratio_hangul.setter
    def ratio_hangul(self, value):
        if value is None:
            return self._pset.RemoveItem("RatioHangul")
        assert 50 <= value <= 200, "값은 50에서 200 사이여야 합니다."
        return self._pset.SetItem("RatioHangul", value)

    @property
    def ratio_latin(self):
        """각 언어별 장평 비율 (영문): 50% - 200%"""
        return self._pset.Item("RatioLatin")

    @ratio_latin.setter
    def ratio_latin(self, value):
        if value is None:
            return self._pset.RemoveItem("RatioLatin")
        assert 50 <= value <= 200, "값은 50에서 200 사이여야 합니다."
        return self._pset.SetItem("RatioLatin", value)

    @property
    def ratio_hanja(self):
        """각 언어별 장평 비율 (한자): 50% - 200%"""
        return self._pset.Item("RatioHanja")

    @ratio_hanja.setter
    def ratio_hanja(self, value):
        if value is None:
            return self._pset.RemoveItem("RatioHanja")
        assert 50 <= value <= 200, "값은 50에서 200 사이여야 합니다."
        return self._pset.SetItem("RatioHanja", value)

    @property
    def ratio_japanese(self):
        """각 언어별 장평 비율 (일본어): 50% - 200%"""
        return self._pset.Item("RatioJapanese")

    @ratio_japanese.setter
    def ratio_japanese(self, value):
        if value is None:
            return self._pset.RemoveItem("RatioJapanese")
        assert 50 <= value <= 200, "값은 50에서 200 사이여야 합니다."
        return self._pset.SetItem("RatioJapanese", value)

    @property
    def ratio_other(self):
        """각 언어별 장평 비율 (기타): 50% - 200%"""
        return self._pset.Item("RatioOther")

    @ratio_other.setter
    def ratio_other(self, value):
        if value is None:
            return self._pset.RemoveItem("RatioOther")
        assert 50 <= value <= 200, "값은 50에서 200 사이여야 합니다."
        return self._pset.SetItem("RatioOther", value)

    @property
    def ratio_symbol(self):
        """각 언어별 장평 비율 (심벌): 50% - 200%"""
        return self._pset.Item("RatioSymbol")

    @ratio_symbol.setter
    def ratio_symbol(self, value):
        if value is None:
            return self._pset.RemoveItem("RatioSymbol")
        assert 50 <= value <= 200, "값은 50에서 200 사이여야 합니다."
        return self._pset.SetItem("RatioSymbol", value)

    @property
    def ratio_user(self):
        """각 언어별 장평 비율 (사용자): 50% - 200%"""
        return self._pset.Item("RatioUser")

    @ratio_user.setter
    def ratio_user(self, value):
        if value is None:
            return self._pset.RemoveItem("RatioUser")
        assert 50 <= value <= 200, "값은 50에서 200 사이여야 합니다."
        return self._pset.SetItem("RatioUser", value)

    @property
    def spacing_hangul(self):
        """각 언어별 자간 (한글): -50% - 50%"""
        return self._pset.Item("SpacingHangul")

    @spacing_hangul.setter
    def spacing_hangul(self, value):
        if value is None:
            return self._pset.RemoveItem("SpacingHangul")
        assert -50 <= value <= 50, "값은 -50에서 50 사이여야 합니다."
        return self._pset.SetItem("SpacingHangul", value)

    @property
    def spacing_latin(self):
        """각 언어별 자간 (영문): -50% - 50%"""
        return self._pset.Item("SpacingLatin")

    @spacing_latin.setter
    def spacing_latin(self, value):
        if value is None:
            return self._pset.RemoveItem("SpacingLatin")
        assert -50 <= value <= 50, "값은 -50에서 50 사이여야 합니다."
        return self._pset.SetItem("SpacingLatin", value)

    @property
    def spacing_hanja(self):
        """각 언어별 자간 (한자): -50% - 50%"""
        return self._pset.Item("SpacingHanja")

    @spacing_hanja.setter
    def spacing_hanja(self, value):
        if value is None:
            return self._pset.RemoveItem("SpacingHanja")
        assert -50 <= value <= 50, "값은 -50에서 50 사이여야 합니다."
        return self._pset.SetItem("SpacingHanja", value)

    @property
    def spacing_japanese(self):
        """각 언어별 자간 (일본어): -50% - 50%"""
        return self._pset.Item("SpacingJapanese")

    @spacing_japanese.setter
    def spacing_japanese(self, value):
        if value is None:
            return self._pset.RemoveItem("SpacingJapanese")
        assert -50 <= value <= 50, "값은 -50에서 50 사이여야 합니다."
        return self._pset.SetItem("SpacingJapanese", value)

    @property
    def spacing_other(self):
        """각 언어별 자간 (기타): -50% - 50%"""
        return self._pset.Item("SpacingOther")

    @spacing_other.setter
    def spacing_other(self, value):
        if value is None:
            return self._pset.RemoveItem("SpacingOther")
        assert -50 <= value <= 50, "값은 -50에서 50 사이여야 합니다."
        return self._pset.SetItem("SpacingOther", value)

    @property
    def spacing_symbol(self):
        """각 언어별 자간 (심벌): -50% - 50%"""
        return self._pset.Item("SpacingSymbol")

    @spacing_symbol.setter
    def spacing_symbol(self, value):
        if value is None:
            return self._pset.RemoveItem("SpacingSymbol")
        assert -50 <= value <= 50, "값은 -50에서 50 사이여야 합니다."
        return self._pset.SetItem("SpacingSymbol", value)

    @property
    def spacing_user(self):
        """각 언어별 자간 (사용자): -50% - 50%"""
        return self._pset.Item("SpacingUser")

    @spacing_user.setter
    def spacing_user(self, value):
        if value is None:
            return self._pset.RemoveItem("SpacingUser")
        assert -50 <= value <= 50, "값은 -50에서 50 사이여야 합니다."
        return self._pset.SetItem("SpacingUser", value)

    @property
    def offset_hangul(self):
        """각 언어별 오프셋 (한글): -100% - 100%"""
        return self._pset.Item("OffsetHangul")

    @offset_hangul.setter
    def offset_hangul(self, value):
        if value is None:
            return self._pset.RemoveItem("OffsetHangul")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("OffsetHangul", value)
    
    @property
    def offset_latin(self):
        """각 언어별 오프셋 (영문): -100% - 100%"""
        return self._pset.Item("OffsetLatin")

    @offset_latin.setter
    def offset_latin(self, value):
        if value is None:
            return self._pset.RemoveItem("OffsetLatin")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("OffsetLatin", value)

    @property
    def offset_hanja(self):
        """각 언어별 오프셋 (한자): -100% - 100%"""
        return self._pset.Item("OffsetHanja")

    @offset_hanja.setter
    def offset_hanja(self, value):
        if value is None:
            return self._pset.RemoveItem("OffsetHanja")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("OffsetHanja", value)

    @property
    def offset_japanese(self):
        """각 언어별 오프셋 (일본어): -100% - 100%"""
        return self._pset.Item("OffsetJapanese")

    @offset_japanese.setter
    def offset_japanese(self, value):
        if value is None:
            return self._pset.RemoveItem("OffsetJapanese")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("OffsetJapanese", value)

    @property
    def offset_other(self):
        """각 언어별 오프셋 (기타): -100% - 100%"""
        return self._pset.Item("OffsetOther")

    @offset_other.setter
    def offset_other(self, value):
        if value is None:
            return self._pset.RemoveItem("OffsetOther")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("OffsetOther", value)

    @property
    def offset_symbol(self):
        """각 언어별 오프셋 (심벌): -100% - 100%"""
        return self._pset.Item("OffsetSymbol")

    @offset_symbol.setter
    def offset_symbol(self, value):
        if value is None:
            return self._pset.RemoveItem("OffsetSymbol")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("OffsetSymbol", value)

    @property
    def offset_user(self):
        """각 언어별 오프셋 (사용자): -100% - 100%"""
        return self._pset.Item("OffsetUser")

    @offset_user.setter
    def offset_user(self, value):
        if value is None:
            return self._pset.RemoveItem("OffsetUser")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("OffsetUser", value)

    @property
    def bold(self):
        """Bold: 0 = off, 1 = on"""
        return self._pset.Item("Bold")

    @bold.setter
    def bold(self, value):
        if value is None:
            return self._pset.RemoveItem("Bold")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("Bold", value)

    @property
    def italic(self):
        """Italic: 0 = off, 1 = on"""
        return self._pset.Item("Italic")

    @italic.setter
    def italic(self, value):
        if value is None:
            return self._pset.RemoveItem("Italic")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("Italic", value)

    @property
    def small_caps(self):
        """Small Caps: 0 = off, 1 = on"""
        return self._pset.Item("SmallCaps")

    @small_caps.setter
    def small_caps(self, value):
        if value is None:
            return self._pset.RemoveItem("SmallCaps")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("SmallCaps", value)

    @property
    def emboss(self):
        """Emboss: 0 = off, 1 = on"""
        return self._pset.Item("Emboss")

    @emboss.setter
    def emboss(self, value):
        if value is None:
            return self._pset.RemoveItem("Emboss")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("Emboss", value)

    @property
    def engrave(self):
        """Engrave: 0 = off, 1 = on"""
        return self._pset.Item("Engrave")

    @engrave.setter
    def engrave(self, value):
        if value is None:
            return self._pset.RemoveItem("Engrave")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("Engrave", value)

    @property
    def superscript(self):
        """Superscript: 0 = off, 1 = on"""
        return self._pset.Item("SuperScript")

    @superscript.setter
    def superscript(self, value):
        if value is None:
            return self._pset.RemoveItem("SuperScript")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("SuperScript", value)

    @property
    def subscript(self):
        """Subscript: 0 = off, 1 = on"""
        return self._pset.Item("SubScript")

    @subscript.setter
    def subscript(self, value):
        if value is None:
            return self._pset.RemoveItem("SubScript")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("SubScript", value)

    @property
    def underline_type(self):
        """밑줄 종류: 0 = none, 1 = bottom, 2 = center, 3 = top"""
        return self._pset.Item("UnderlineType")

    @underline_type.setter
    def underline_type(self, value):
        if value is None:
            return self._pset.RemoveItem("UnderlineType")
        assert value in [0, 1, 2, 3], "값은 0, 1, 2, 3 중 하나여야 합니다."
        return self._pset.SetItem("UnderlineType", value)

    @property
    def outline_type(self):
        """외곽선 종류: 0 = none, 1 = solid, 2 = dot, 3 = thick, 4 = dash, 5 = dashdot, 6 = dashdotdot"""
        return self._pset.Item("OutlineType")

    @outline_type.setter
    def outline_type(self, value):
        if value is None:
            return self._pset.RemoveItem("OutlineType")
        assert value in [0, 1, 2, 3, 4, 5, 6], "값은 0에서 6 사이여야 합니다."
        return self._pset.SetItem("OutlineType", value)

    @property
    def shadow_type(self):
        """그림자 종류: 0 = none, 1 = drop, 2 = continuous"""
        return self._pset.Item("ShadowType")

    @shadow_type.setter
    def shadow_type(self, value):
        if value is None:
            return self._pset.RemoveItem("ShadowType")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("ShadowType", value)

    @property
    def text_color(self):
        """글자색 (COLORREF, 0x00BBGGRR)"""
        return self._pset.Item("TextColor")

    @text_color.setter
    def text_color(self, value):
        if value is None:
            return self._pset.RemoveItem("TextColor")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("TextColor", value)

    @property
    def shade_color(self):
        """음영색 (COLORREF, 0x00BBGGRR)"""
        return self._pset.Item("ShadeColor")

    @shade_color.setter
    def shade_color(self, value):
        if value is None:
            return self._pset.RemoveItem("ShadeColor")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("ShadeColor", value)

    @property
    def underline_shape(self):
        """밑줄 모양"""
        return self._pset.Item("UnderlineShape")

    @underline_shape.setter
    def underline_shape(self, value):
        if value is None:
            return self._pset.RemoveItem("UnderlineShape")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("UnderlineShape", value)

    @property
    def underline_color(self):
        """밑줄 색상 (COLORREF, 0x00BBGGRR)"""
        return self._pset.Item("UnderlineColor")

    @underline_color.setter
    def underline_color(self, value):
        if value is None:
            return self._pset.RemoveItem("UnderlineColor")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("UnderlineColor", value)

    @property
    def shadow_offset_x(self):
        """그림자 간격 (X 방향): -100% - 100%"""
        return self._pset.Item("ShadowOffsetX")

    @shadow_offset_x.setter
    def shadow_offset_x(self, value):
        if value is None:
            return self._pset.RemoveItem("ShadowOffsetX")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("ShadowOffsetX", value)

    @property
    def shadow_offset_y(self):
        """그림자 간격 (Y 방향): -100% - 100%"""
        return self._pset.Item("ShadowOffsetY")

    @shadow_offset_y.setter
    def shadow_offset_y(self, value):
        if value is None:
            return self._pset.RemoveItem("ShadowOffsetY")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("ShadowOffsetY", value)

    @property
    def shadow_color(self):
        """그림자 색 (COLORREF, 0x00BBGGRR)"""
        return self._pset.Item("ShadowColor")

    @shadow_color.setter
    def shadow_color(self, value):
        if value is None:
            return self._pset.RemoveItem("ShadowColor")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("ShadowColor", value)

    @property
    def strikeout_type(self):
        """취소선 종류: 0 = none, 1 = red single, 2 = red double, 3 = text single, 4 = text double"""
        return self._pset.Item("StrikeOutType")

    @strikeout_type.setter
    def strikeout_type(self, value):
        if value is None:
            return self._pset.RemoveItem("StrikeOutType")
        assert value in [0, 1, 2, 3, 4], "값은 0에서 4 사이여야 합니다."
        return self._pset.SetItem("StrikeOutType", value)

    @property
    def diac_sym_mark(self):
        """강조점 종류: 0 = none, 1 = 검정 동그라미, 2 = 속 빈 동그라미"""
        return self._pset.Item("DiacSymMark")

    @diac_sym_mark.setter
    def diac_sym_mark(self, value):
        if value is None:
            return self._pset.RemoveItem("DiacSymMark")
        assert value in [0, 1, 2], "값은 0에서 2 사이여야 합니다."
        return self._pset.SetItem("DiacSymMark", value)

    @property
    def use_font_space(self):
        """글꼴에 어울리는 빈칸: 0 = off, 1 = on"""
        return self._pset.Item("UseFontSpace")

    @use_font_space.setter
    def use_font_space(self, value):
        if value is None:
            return self._pset.RemoveItem("UseFontSpace")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("UseFontSpace", value)

    @property
    def use_kerning(self):
        """커닝: 0 = off, 1 = on"""
        return self._pset.Item("UseKerning")

    @use_kerning.setter
    def use_kerning(self, value):
        if value is None:
            return self._pset.RemoveItem("UseKerning")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("UseKerning", value)

    @property
    def height(self):
        """글자 크기 (HWPUNIT)"""
        return self._pset.Item("Height")

    @height.setter
    def height(self, value):
        if value is None:
            return self._pset.RemoveItem("Height")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("Height", value)

    @property
    def border_fill(self):
        """테두리/배경 (BorderFill)"""
        return self._pset.Item("BorderFill")

    @border_fill.setter
    def border_fill(self, value):
        if value is None:
            return self._pset.RemoveItem("BorderFill")
        # Assuming `BorderFill` is a class or set object
        assert isinstance(value, BorderFill), "값은 BorderFill 객체이어야 합니다."
        return self._pset.SetItem("BorderFill", value)

# %% ../nbs/02_api/02_parameters.ipynb 21
class DrawFillAttr(ParameterSet):
    """### DrawFillAttr

31\) DrawFillAttr : 그리기 개체의 채우기 속성


| Item ID | Type | SubType | Description |
| --- | --- | --- | --- |
| Type | PIT\_UI |  | 배경 유형0 \= 채우기 없음1 \= 면색 또는 무늬색2 \= 그림3 \= 그러데이션 |
| GradationType | PIT\_I |  | 배경 유형이 그러데이션일 때 그러데이션 형태1 \= 줄무늬형2 \= 원형3 \= 원뿔형4 \= 사각형 |
| GradationAngle | PIT\_I |  | 그러데이션의 기울임(시작각) |
| GradationCenterX | PIT\_I |  | 그러데이션의 가로중심(중심 X 좌표) |
| GradationCenterY | PIT\_I |  | 그러데이션의 가로중심(중심 Y 좌표) |
| GradationStep | PIT\_I |  | 그러데이션 번짐 정도 (0\..100\) |
| GradationColorNum | PIT\_I |  | 그러데이션의 색 수 |
| GradationColor | PIT\_ARRAY | PIT\_I | 그러데이션의 색깔(시작색, 중간색1,..중간색 n\-2, 끝색) 2\<\= n \<\=10 |
| GradationIndexPos | PIT\_ARRAY | PIT\_I | 그러데이션 다음 색깔과의 거리(얼마나 번지고 나서 다음색깔로 가는가) |
| GradationStepCenter | PIT\_UI1 |  | 그러데이션 번짐 정도의 중심 (0\..100\) |
| GradationAlpha | PIT\_UI1 |  | 그러데이션 투명도 (한글2007에 새로 추가) |
| WinBrushFaceColor | PIT\_UI |  | 면 색 (RGB 0x00BBGGRR) (한글2007에 새로 추가) |
| WinBrushHatchColor | PIT\_UI |  | 무늬 색 (RGB 0x00BBGGRR) (한글2007에 새로 추가) |
| WinBrushFaceStyle | PIT\_I1 |  | 무늬 스타일 (한글2007에 새로 추가)  | 0 \= 1 \= 2 \= 3 \= | 4 \= 5 \= 6 \= | | --- | --- | |
| WinBrushAlpha | PIT\_UI |  | 면/무늬 색 투명도 (한글2007에 새로 추가) |
| FileName | PIT\_BSTR |  | ShapeObject의 배경을 그림으로 선택했을 경우. 또는 그림개체일 경우의 그림파일 경로 |
| Embedded | PIT\_UI1 |  | 그림이 문서에 직접 삽입(TRUE) / 파일로 연결(FALSE) |
| PicEffect | PIT\_UI1 |  | 그림 효과  0 \= 실제 이미지 그대로1 \= 그레이스케일2 \= 흑백 효과 |
| Brightness | PIT\_I1 |  | 명도 (\-100 \~ 100\) |
| Contrast | PIT\_I1 |  | 밝기 (\-100 \~ 100\) |
| Reverse | PIT\_UI1 |  | 반전 유무 |
| DrawFillImageType | PIT\_I |  | ShapeObject의 배경일 경우에만 의미 있는 아이템, 배경을 채우는 방식을 결정한다. (그림개체에는 해당사항 없음)0 \= 바둑판식으로1 \= 가로/위만 바둑판식으로 배열2 \= 가로/아래만 바둑판식으로 배열3 \= 세로/왼쪽만 바둑판식으로 배열4 \= 세로/오른쪽만 바둑판식으로 배열5 \= 크기에 맞추어6 \= 가운데로7 \= 가운데 위로8 \= 가운데 아래로9 \= 왼쪽 가운데로10 \= 왼쪽 위로11 \= 왼쪽 아래로12 \= 오른쪽 가운데로13 \= 오른쪽 위로14 \= 오른쪽 아래로 |
| SkipLeft | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 왼쪽 자르기 |
| SkipRight | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 오른쪽 자르기 |
| SkipTop | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 위 자르기 |
| SkipBottom | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 아래 자르기 |
| OriginalSizeX | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 원본 크기 X size |
| OriginalSizeY | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 원본 크기 Y size |
| InsideMarginLeft | PIT\_I4 |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 안쪽 여백. (왼쪽) |
| InsideMarginRight | PIT\_I4 |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 안쪽 여백. (오른쪽) |
| InsideMarginTop | PIT\_I4 |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 안쪽 여백. (위) |
| InsideMarginBottom | PIT\_I4 |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 안쪽 여백. (아래) |
| WindowsBrush | PIT\_UI1 |  | 현재 선택된 brush의 type이 면/무늬 브러시인가를 나타냄 |
| GradationBrush | PIT\_UI1 |  | 현재 선택된 brush의 type이 그러데이션 브러시인가를 나타냄 |
| ImageBrush | PIT\_UI1 |  | 현재 선택된 brush의 type이 그림 브러시인가를 나타냄 |
| ImageCreateOnDrag | PIT\_UI1 |  | 그림 개체 생성 시 마우스로 끌어 생성할지 여부(한글2007에 새로 추가) |
| ImageAlpha | PIT\_UI1 |  | 그림 개체/배경 투명도 (한글2007에 새로 추가) |

 """

    @property
    def type(self):
        """배경 유형: 0 = 채우기 없음, 1 = 단색 또는 무늬 채우기, 2 = 그림, 3 = 그라데이션"""
        return self._pset.Item("Type")

    @type.setter
    def type(self, value):
        if value is None:
            return self._pset.RemoveItem("Type")
        assert value in [0, 1, 2, 3], "값은 0, 1, 2, 3 중 하나여야 합니다."
        return self._pset.SetItem("Type", value)
    
    @property
    def gradation_type(self):
        """배경 유형이 그라데이션일 때 그라데이션 형태"""
        return self._pset.Item("GradationType")

    @gradation_type.setter
    def gradation_type(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationType")
        assert value in [1, 2, 3, 4], "값은 1=선형, 2=원형, 3=원뿔형, 4=사각형 중 하나여야 합니다."
        return self._pset.SetItem("GradationType", value)

    @property
    def gradation_angle(self):
        """그라데이션의 기울기(회전 각도)"""
        return self._pset.Item("GradationAngle")

    @gradation_angle.setter
    def gradation_angle(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationAngle")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("GradationAngle", value)

    @property
    def gradation_center_x(self):
        """그라데이션의 가로 중심(X 좌표)"""
        return self._pset.Item("GradationCenterX")

    @gradation_center_x.setter
    def gradation_center_x(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationCenterX")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("GradationCenterX", value)

    @property
    def gradation_center_y(self):
        """그라데이션의 세로 중심(Y 좌표)"""
        return self._pset.Item("GradationCenterY")

    @gradation_center_y.setter
    def gradation_center_y(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationCenterY")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("GradationCenterY", value)

    @property
    def gradation_step(self):
        """그라데이션 단계 설정 (0..100)"""
        return self._pset.Item("GradationStep")

    @gradation_step.setter
    def gradation_step(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationStep")
        assert 0 <= value <= 100, "값은 0과 100 사이의 정수여야 합니다."
        return self._pset.SetItem("GradationStep", value)

    @property
    def gradation_color_num(self):
        """그라데이션의 색 수"""
        return self._pset.Item("GradationColorNum")

    @gradation_color_num.setter
    def gradation_color_num(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationColorNum")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("GradationColorNum", value)

    @property
    def gradation_color(self):
        """그라데이션의 색상 (시작색, 중간색1,..중간색 n-2, 끝색)"""
        return self._pset.Item("GradationColor")

    @gradation_color.setter
    def gradation_color(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationColor")
        assert isinstance(value, list) and 2 <= len(value) <= 10, "값은 길이가 2에서 10 사이인 리스트여야 합니다."
        return self._pset.SetItem("GradationColor", value)

    @property
    def gradation_index_pos(self):
        """그라데이션 단계 색상들과의 위치"""
        return self._pset.Item("GradationIndexPos")

    @gradation_index_pos.setter
    def gradation_index_pos(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationIndexPos")
        assert isinstance(value, list), "값은 리스트여야 합니다."
        return self._pset.SetItem("GradationIndexPos", value)

    @property
    def gradation_step_center(self):
        """그라데이션 단계 설정의 중심 (0..100)"""
        return self._pset.Item("GradationStepCenter")

    @gradation_step_center.setter
    def gradation_step_center(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationStepCenter")
        assert 0 <= value <= 100, "값은 0과 100 사이의 정수여야 합니다."
        return self._pset.SetItem("GradationStepCenter", value)

    @property
    def gradation_alpha(self):
        """그라데이션 투명도"""
        return self._pset.Item("GradationAlpha")

    @gradation_alpha.setter
    def gradation_alpha(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationAlpha")
        assert 0 <= value <= 255, "값은 0과 255 사이의 정수여야 합니다."
        return self._pset.SetItem("GradationAlpha", value)

    @property
    def win_brush_face_color(self):
        """단색 (RGB 0x00BBGGRR)"""
        return self._pset.Item("WinBrushFaceColor")

    @win_brush_face_color.setter
    def win_brush_face_color(self, value):
        if value is None:
            return self._pset.RemoveItem("WinBrushFaceColor")
        assert isinstance(value, int) and 0 <= value <= 0xFFFFFF, "값은 0x00BBGGRR 형식의 정수여야 합니다."
        return self._pset.SetItem("WinBrushFaceColor", value)

    @property
    def win_brush_hatch_color(self):
        """무늬 (RGB 0x00BBGGRR)"""
        return self._pset.Item("WinBrushHatchColor")

    @win_brush_hatch_color.setter
    def win_brush_hatch_color(self, value):
        if value is None:
            return self._pset.RemoveItem("WinBrushHatchColor")
        assert isinstance(value, int) and 0 <= value <= 0xFFFFFF, "값은 0x00BBGGRR 형식의 정수여야 합니다."
        return self._pset.SetItem("WinBrushHatchColor", value)

    @property
    def win_brush_face_style(self):
        """무늬 스타일"""
        return self._pset.Item("WinBrushFaceStyle")

    @win_brush_face_style.setter
    def win_brush_face_style(self, value):
        if value is None:
            return self._pset.RemoveItem("WinBrushFaceStyle")
        assert 0 <= value <= 6, "값은 0에서 6 사이의 정수여야 합니다."
        return self._pset.SetItem("WinBrushFaceStyle", value)

    @property
    def win_brush_alpha(self):
        """단색/무늬 투명도"""
        return self._pset.Item("WinBrushAlpha")

    @win_brush_alpha.setter
    def win_brush_alpha(self, value):
        if value is None:
            return self._pset.RemoveItem("WinBrushAlpha")
        assert 0 <= value <= 255, "값은 0과 255 사이의 정수여야 합니다."
        return self._pset.SetItem("WinBrushAlpha", value)
    
    @property
    def filename(self):
        """ShapeObject의 배경을 그림으로 선택했을 경우 또는 그림개체일 경우의 그림파일 경로"""
        return self._pset.Item("FileName")

    @filename.setter
    def filename(self, value):
        if value is None:
            return self._pset.RemoveItem("FileName")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FileName", value)

    @property
    def embedded(self):
        """그림이 문서에 직접 삽입(TRUE) / 파일로 연결(FALSE)"""
        return self._pset.Item("Embedded")

    @embedded.setter
    def embedded(self, value):
        if value is None:
            return self._pset.RemoveItem("Embedded")
        assert value in [0, 1], "값은 0(FALSE) 또는 1(TRUE)이어야 합니다."
        return self._pset.SetItem("Embedded", value)

    @property
    def pic_effect(self):
        """그림 효과: 0 = 실제 이미지 그대로, 1 = 그레이스케일, 2 = 흑백 효과"""
        return self._pset.Item("PicEffect")

    @pic_effect.setter
    def pic_effect(self, value):
        if value is None:
            return self._pset.RemoveItem("PicEffect")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("PicEffect", value)

    @property
    def brightness(self):
        """명도 (-100 ~ 100)"""
        return self._pset.Item("Brightness")

    @brightness.setter
    def brightness(self, value):
        if value is None:
            return self._pset.RemoveItem("Brightness")
        assert -100 <= value <= 100, "값은 -100과 100 사이의 정수여야 합니다."
        return self._pset.SetItem("Brightness", value)

    @property
    def contrast(self):
        """대비 (-100 ~ 100)"""
        return self._pset.Item("Contrast")

    @contrast.setter
    def contrast(self, value):
        if value is None:
            return self._pset.RemoveItem("Contrast")
        assert -100 <= value <= 100, "값은 -100과 100 사이의 정수여야 합니다."
        return self._pset.SetItem("Contrast", value)

    @property
    def reverse(self):
        """반전 유무"""
        return self._pset.Item("Reverse")

    @reverse.setter
    def reverse(self, value):
        if value is None:
            return self._pset.RemoveItem("Reverse")
        assert value in [0, 1], "값은 0(FALSE) 또는 1(TRUE)이어야 합니다."
        return self._pset.SetItem("Reverse", value)

    @property
    def draw_fill_image_type(self):
        """배경을 채우는 방식"""
        return self._pset.Item("DrawFillImageType")

    @draw_fill_image_type.setter
    def draw_fill_image_type(self, value):
        if value is None:
            return self._pset.RemoveItem("DrawFillImageType")
        assert 0 <= value <= 14, "값은 0에서 14 사이의 정수여야 합니다."
        return self._pset.SetItem("DrawFillImageType", value)

    @property
    def skip_left(self):
        """왼쪽 자르기"""
        return self._pset.Item("SkipLeft")

    @skip_left.setter
    def skip_left(self, value):
        if value is None:
            return self._pset.RemoveItem("SkipLeft")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("SkipLeft", value)

    @property
    def skip_right(self):
        """오른쪽 자르기"""
        return self._pset.Item("SkipRight")

    @skip_right.setter
    def skip_right(self, value):
        if value is None:
            return self._pset.RemoveItem("SkipRight")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("SkipRight", value)

    @property
    def skip_top(self):
        """위 자르기"""
        return self._pset.Item("SkipTop")

    @skip_top.setter
    def skip_top(self, value):
        if value is None:
            return self._pset.RemoveItem("SkipTop")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("SkipTop", value)

    @property
    def skip_bottom(self):
        """아래 자르기"""
        return self._pset.Item("SkipBottom")

    @skip_bottom.setter
    def skip_bottom(self, value):
        if value is None:
            return self._pset.RemoveItem("SkipBottom")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("SkipBottom", value)

    @property
    def original_size_x(self):
        """이미지 원본 크기 X size"""
        return self._pset.Item("OriginalSizeX")

    @original_size_x.setter
    def original_size_x(self, value):
        if value is None:
            return self._pset.RemoveItem("OriginalSizeX")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("OriginalSizeX", value)

    @property
    def original_size_y(self):
        """이미지 원본 크기 Y size"""
        return self._pset.Item("OriginalSizeY")

    @original_size_y.setter
    def original_size_y(self, value):
        if value is None:
            return self._pset.RemoveItem("OriginalSizeY")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("OriginalSizeY", value)
    
    @property
    def inside_margin_left(self):
        """이미지 안쪽 여백 (왼쪽)"""
        return self._pset.Item("InsideMarginLeft")

    @inside_margin_left.setter
    def inside_margin_left(self, value):
        if value is None:
            return self._pset.RemoveItem("InsideMarginLeft")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("InsideMarginLeft", value)

    @property
    def inside_margin_right(self):
        """이미지 안쪽 여백 (오른쪽)"""
        return self._pset.Item("InsideMarginRight")

    @inside_margin_right.setter
    def inside_margin_right(self, value):
        if value is None:
            return self._pset.RemoveItem("InsideMarginRight")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("InsideMarginRight", value)

    @property
    def inside_margin_top(self):
        """이미지 안쪽 여백 (위)"""
        return self._pset.Item("InsideMarginTop")

    @inside_margin_top.setter
    def inside_margin_top(self, value):
        if value is None:
            return self._pset.RemoveItem("InsideMarginTop")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("InsideMarginTop", value)

    @property
    def inside_margin_bottom(self):
        """이미지 안쪽 여백 (아래)"""
        return self._pset.Item("InsideMarginBottom")

    @inside_margin_bottom.setter
    def inside_margin_bottom(self, value):
        if value is None:
            return self._pset.RemoveItem("InsideMarginBottom")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("InsideMarginBottom", value)

    @property
    def windows_brush(self):
        """현재 선택된 brush의 type이 면/무늬 브러시인가"""
        return self._pset.Item("WindowsBrush")

    @windows_brush.setter
    def windows_brush(self, value):
        if value is None:
            return self._pset.RemoveItem("WindowsBrush")
        assert value in [0, 1], "값은 0 (아님) 또는 1 (맞음)이어야 합니다."
        return self._pset.SetItem("WindowsBrush", value)

    @property
    def gradation_brush(self):
        """현재 선택된 brush의 type이 그러데이션 브러시인가"""
        return self._pset.Item("GradationBrush")

    @gradation_brush.setter
    def gradation_brush(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationBrush")
        assert value in [0, 1], "값은 0 (아님) 또는 1 (맞음)이어야 합니다."
        return self._pset.SetItem("GradationBrush", value)

    @property
    def image_brush(self):
        """현재 선택된 brush의 type이 그림 브러시인가"""
        return self._pset.Item("ImageBrush")

    @image_brush.setter
    def image_brush(self, value):
        if value is None:
            return self._pset.RemoveItem("ImageBrush")
        assert value in [0, 1], "값은 0 (아님) 또는 1 (맞음)이어야 합니다."
        return self._pset.SetItem("ImageBrush", value)

    @property
    def image_create_on_drag(self):
        """그림 개체 생성 시 마우스로 끌어 생성 여부"""
        return self._pset.Item("ImageCreateOnDrag")

    @image_create_on_drag.setter
    def image_create_on_drag(self, value):
        if value is None:
            return self._pset.RemoveItem("ImageCreateOnDrag")
        assert value in [0, 1], "값은 0 (아님) 또는 1 (맞음)이어야 합니다."
        return self._pset.SetItem("ImageCreateOnDrag", value)

    @property
    def image_alpha(self):
        """그림 개체/배경 투명도"""
        return self._pset.Item("ImageAlpha")

    @image_alpha.setter
    def image_alpha(self, value):
        if value is None:
            return self._pset.RemoveItem("ImageAlpha")
        assert isinstance(value, int) and 0 <= value <= 255, "값은 0에서 255 사이의 정수여야 합니다."
        return self._pset.SetItem("ImageAlpha", value)

# %% ../nbs/02_api/02_parameters.ipynb 22
class TabDef(ParameterSet):
    """
   ### TabDef

113\) TabDef : 탭 정의

| Item ID | Type | SubType | Description |
| --- | --- | --- | --- |
| AutoTabLeft | PIT\_UI1 |  | 문단 왼쪽 끝 탭 (on / off) |
| AutoTabRight | PIT\_UI1 |  | 문단 오른쪽 끝 탭 (on / off) |
| TabItem | PIT\_ARRAY | PIT\_I | 각각의 탭 정의. 하나의 탭 아이템은 세 개의 인수로 표현되어 있음.(n \* 3 \+ 0\) \- PIT\_I : 탭 위치 (URC)(n \* 3 \+ 1\) \- PIT\_I : 채울 모양 (아래참조)(n \* 3 \+ 2\) \- PIT\_I : 탭 종류 (아래참조.)채울 모양 :선 종류, 탭 종류 :0 \= 왼쪽 1 \= 오른쪽2 \= 가운데3 \= 소수점 |

 """

    @property
    def auto_tab_left(self):
        """문단 왼쪽 탭 설정 (on / off)"""
        return self._pset.Item("AutoTabLeft")

    @auto_tab_left.setter
    def auto_tab_left(self, value):
        if value is None:
            return self._pset.RemoveItem("AutoTabLeft")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("AutoTabLeft", value)

    @property
    def auto_tab_right(self):
        """문단 오른쪽 탭 설정 (on / off)"""
        return self._pset.Item("AutoTabRight")

    @auto_tab_right.setter
    def auto_tab_right(self, value):
        if value is None:
            return self._pset.RemoveItem("AutoTabRight")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("AutoTabRight", value)

    @property
    def tab_item(self):
        """탭 정의 목록"""
        return self._pset.Item("TabItem")

    @tab_item.setter
    def tab_item(self, value):
        if value is None:
            return self._pset.RemoveItem("TabItem")
        assert isinstance(value, list), "값은 리스트 형식이어야 합니다."
        for item in value:
            assert isinstance(item, int), "리스트의 각 항목은 정수형이어야 합니다."
        return self._pset.SetItem("TabItem", value)



# %% ../nbs/02_api/02_parameters.ipynb 23
class NumberingShape(ParameterSet):
    """
    ### NumberingShape

    | Item ID               | Type      | SubType   | Description |
    |-----------------------|-----------|-----------|-------------|
    | HasCharShapeLevel0 ~ HasCharShapeLevel6 | PIT_UI1   |           | 7단 수준별 지정 여부 (0 = 기본값, 1 = 지정) |
    | CharShapeLevel0 ~ CharShapeLevel6       | PIT_SET   | CharShape | 수준별 글자 모양 지정 |
    | WidthAdjustLevel0 ~ WidthAdjustLevel6   | PIT_I     |           | 수준별 너비 조정 값 (HWPUNIT) |
    | TextOffsetLevel0 ~ TextOffsetLevel6     | PIT_I     |           | 수준별 텍스트 오프셋 (percent or HWPUNIT) |
    | AlignmentLevel0 ~ AlignmentLevel6       | PIT_UI1   |           | 수준별 정렬 (0 = 왼쪽, 1 = 가운데, 2 = 오른쪽) |
    | UseInstWidthLevel0 ~ UseInstWidthLevel6 | PIT_UI1   |           | 수준별 너비를 문서 내부 너비에 맞출지 여부 |
    | AutoIndentLevel0 ~ AutoIndentLevel6     | PIT_UI1   |           | 수준별 자동 들여쓰기 여부 |
    | TextOffsetTypeLevel0 ~ TextOffsetTypeLevel6 | PIT_UI1 |           | 텍스트 오프셋 타입 (0 = 기본값, 1 = HWPUNIT) |
    | StrFormatLevel0 ~ StrFormatLevel6       | PIT_BSTR  |           | 수준별 문자열 포맷 |
    | NumFormatLevel0 ~ NumFormatLevel6       | PIT_UI1   |           | 수준별 번호 포맷 |
    | StartNumber                            | PIT_UI2   |           | 시작 번호 (0 = 기본값, n = 지정 번호) |
    | NewList                                | PIT_UI1   |           | 새 목록 생성 여부 |

    """

    def _validate_ui1(self, value):
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."

    def _validate_alignment(self, value):
        assert value in [0, 1, 2], "값은 0 (왼쪽), 1 (가운데), 2 (오른쪽)이어야 합니다."

    @property
    def start_number(self):
        return self._pset.Item("StartNumber")

    @start_number.setter
    def start_number(self, value):
        if value is None:
            return self._pset.RemoveItem("StartNumber")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("StartNumber", value)

    @property
    def new_list(self):
        return self._pset.Item("NewList")

    @new_list.setter
    def new_list(self, value):
        if value is None:
            return self._pset.RemoveItem("NewList")
        self._validate_ui1(value)
        return self._pset.SetItem("NewList", value)

    def _get_level_property(self, prefix, level):
        return self._pset.Item(f"{prefix}Level{level}")

    def _set_level_property(self, prefix, level, value):
        if value is None:
            return self._pset.RemoveItem(f"{prefix}Level{level}")
        return self._pset.SetItem(f"{prefix}Level{level}", value)

    for level in range(7):
        exec(f"""
        @property
        def has_char_shape_level{level}(self):
            return self._get_level_property('HasCharShape', {level})

        @has_char_shape_level{level}.setter
        def has_char_shape_level{level}(self, value):
            self._validate_ui1(value)
            self._set_level_property('HasCharShape', {level}, value)

        @property
        def char_shape_level{level}(self):
            return self._get_level_property('CharShape', {level})

        @char_shape_level{level}.setter
        def char_shape_level{level}(self, value):
            self._set_level_property('CharShape', {level}, value)

        @property
        def width_adjust_level{level}(self):
            return self._get_level_property('WidthAdjust', {level})

        @width_adjust_level{level}.setter
        def width_adjust_level{level}(self, value):
            self._set_level_property('WidthAdjust', {level}, value)

        @property
        def text_offset_level{level}(self):
            return self._get_level_property('TextOffset', {level})

        @text_offset_level{level}.setter
        def text_offset_level{level}(self, value):
            self._set_level_property('TextOffset', {level}, value)

        @property
        def alignment_level{level}(self):
            return self._get_level_property('Alignment', {level})

        @alignment_level{level}.setter
        def alignment_level{level}(self, value):
            self._validate_alignment(value)
            self._set_level_property('Alignment', {level}, value)

        @property
        def use_inst_width_level{level}(self):
            return self._get_level_property('UseInstWidth', {level})

        @use_inst_width_level{level}.setter
        def use_inst_width_level{level}(self, value):
            self._validate_ui1(value)
            self._set_level_property('UseInstWidth', {level}, value)

        @property
        def auto_indent_level{level}(self):
            return self._get_level_property('AutoIndent', {level})

        @auto_indent_level{level}.setter
        def auto_indent_level{level}(self, value):
            self._validate_ui1(value)
            self._set_level_property('AutoIndent', {level}, value)

        @property
        def text_offset_type_level{level}(self):
            return self._get_level_property('TextOffsetType', {level})

        @text_offset_type_level{level}.setter
        def text_offset_type_level{level}(self, value):
            self._validate_ui1(value)
            self._set_level_property('TextOffsetType', {level}, value)

        @property
        def str_format_level{level}(self):
            return self._get_level_property('StrFormat', {level})

        @str_format_level{level}.setter
        def str_format_level{level}(self, value):
            self._set_level_property('StrFormat', {level}, value)

        @property
        def num_format_level{level}(self):
            return self._get_level_property('NumFormat', {level})

        @num_format_level{level}.setter
        def num_format_level{level}(self, value):
            self._validate_ui1(value)
            self._set_level_property('NumFormat', {level}, value)
        """)


# %% ../nbs/02_api/02_parameters.ipynb 24
class BulletShape(ParameterSet):
    """
    ### BulletShape

    | Item ID        | Type     | SubType        | Description |
    |----------------|----------|----------------|-------------|
    | HasCharShape  | PIT_UI1  |                | 글자 모양 사용 여부: 0 = 기본, 1 = 사용자 정의 |
    | CharShape     | PIT_SET  | CharShape      | 글자 모양 (HasCharShape가 1일 경우 사용) |
    | WidthAdjust   | PIT_I    |                | 글자 크기 보정 값 (HWPUNIT) |
    | TextOffset    | PIT_I    |                | 텍스트 오프셋 (percent or HWPUNIT) |
    | Alignment     | PIT_UI1  |                | 정렬 방식: 0 = 왼쪽, 1 = 가운데, 2 = 오른쪽 |
    | UseInstWidth  | PIT_UI1  |                | 인스턴스 폭 사용 여부 (on/off) |
    | AutoIndent    | PIT_UI1  |                | 자동 들여쓰기 (on/off) |
    | TextOffsetType| PIT_UI1  |                | 텍스트 오프셋 타입: 0 = percent, 1 = HWPUNIT |
    | BulletChar    | PIT_UI2  |                | 글머리 기호 문자 |
    | HasImage      | PIT_UI1  |                | 이미지 글머리 기호 여부: 0 = 없음, 1 = 있음 |
    | BulletImage   | PIT_SET  | DrawImageAttr  | 글머리 기호 이미지 |
    """

    @property
    def has_char_shape(self):
        """글자 모양 사용 여부"""
        return self._pset.Item("HasCharShape")

    @has_char_shape.setter
    def has_char_shape(self, value):
        if value is None:
            return self._pset.RemoveItem("HasCharShape")
        assert value in [0, 1], "값은 0 (기본) 또는 1 (사용자 정의)이어야 합니다."
        return self._pset.SetItem("HasCharShape", value)

    @property
    def char_shape(self):
        """글자 모양"""
        return self._pset.Item("CharShape")

    @char_shape.setter
    def char_shape(self, value):
        if value is None:
            return self._pset.RemoveItem("CharShape")
        assert isinstance(value, CharShape), "값은 CharShape 객체여야 합니다."
        return self._pset.SetItem("CharShape", value)

    @property
    def width_adjust(self):
        """글자 크기 보정 값"""
        return self._pset.Item("WidthAdjust")

    @width_adjust.setter
    def width_adjust(self, value):
        if value is None:
            return self._pset.RemoveItem("WidthAdjust")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("WidthAdjust", value)

    @property
    def text_offset(self):
        """텍스트 오프셋"""
        return self._pset.Item("TextOffset")

    @text_offset.setter
    def text_offset(self, value):
        if value is None:
            return self._pset.RemoveItem("TextOffset")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("TextOffset", value)

    @property
    def alignment(self):
        """정렬 방식"""
        return self._pset.Item("Alignment")

    @alignment.setter
    def alignment(self, value):
        if value is None:
            return self._pset.RemoveItem("Alignment")
        assert value in [0, 1, 2], "값은 0 (왼쪽), 1 (가운데), 2 (오른쪽) 중 하나여야 합니다."
        return self._pset.SetItem("Alignment", value)

    @property
    def use_inst_width(self):
        """인스턴스 폭 사용 여부"""
        return self._pset.Item("UseInstWidth")

    @use_inst_width.setter
    def use_inst_width(self, value):
        if value is None:
            return self._pset.RemoveItem("UseInstWidth")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("UseInstWidth", value)

    @property
    def auto_indent(self):
        """자동 들여쓰기"""
        return self._pset.Item("AutoIndent")

    @auto_indent.setter
    def auto_indent(self, value):
        if value is None:
            return self._pset.RemoveItem("AutoIndent")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("AutoIndent", value)

    @property
    def text_offset_type(self):
        """텍스트 오프셋 타입"""
        return self._pset.Item("TextOffsetType")

    @text_offset_type.setter
    def text_offset_type(self, value):
        if value is None:
            return self._pset.RemoveItem("TextOffsetType")
        assert value in [0, 1], "값은 0 (percent) 또는 1 (HWPUNIT)이어야 합니다."
        return self._pset.SetItem("TextOffsetType", value)

    @property
    def bullet_char(self):
        """글머리 기호 문자"""
        return self._pset.Item("BulletChar")

    @bullet_char.setter
    def bullet_char(self, value):
        if value is None:
            return self._pset.RemoveItem("BulletChar")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("BulletChar", value)

    @property
    def has_image(self):
        """이미지 글머리 기호 여부"""
        return self._pset.Item("HasImage")

    @has_image.setter
    def has_image(self, value):
        if value is None:
            return self._pset.RemoveItem("HasImage")
        assert value in [0, 1], "값은 0 (없음) 또는 1 (있음)이어야 합니다."
        return self._pset.SetItem("HasImage", value)

    @property
    def bullet_image(self):
        """글머리 기호 이미지"""
        return self._pset.Item("BulletImage")

    @bullet_image.setter
    def bullet_image(self, value):
        if value is None:
            return self._pset.RemoveItem("BulletImage")
        assert isinstance(value, DrawImageAttr), "값은 DrawImageAttr 객체여야 합니다."
        return self._pset.SetItem("BulletImage", value)


# %% ../nbs/02_api/02_parameters.ipynb 25
class DrawImageAttr(ParameterSet):
    """
    ### DrawImageAttr

32\) DrawImageAttr : 그림 개체 속성

ImageAttr(한글2005)에서 DrawImageAttr로 이름이 변경되었다. 그림 개체의 속성을 지정하기 위한 파라메터셋.

DrawFillAttr에서 그림과 관련된 속성만 빼서 파라메터셋으로 지정되었다.

현재 DrawFillAttr와 상속관계가 지정되지 않았다. (차후 상속관계로 묶일 예정)


| Item ID | Type | SubType | Description |
| --- | --- | --- | --- |
| FileName | PIT\_BSTR |  | ShapeObject의 배경을 그림으로 선택했을 경우 또는 그림개체일 경우의 그림파일 경로 |
| Embedded | PIT\_UI1 |  | 그림이 문서에 직접 삽입(TRUE) / 파일로 연결(FALSE) |
| PicEffect | PIT\_UI1 |  | 그림 효과  0 \= 실제 이미지 그대로1 \= 그레이스케일2 \= 흑백 효과 |
| Brightness | PIT\_I1 |  | 명도 (\-100 \~ 100\) |
| Contrast | PIT\_I1 |  | 밝기 (\-100 \~ 100\) |
| Reverse | PIT\_UI1 |  | 반전 유무 |
| DrawFillImageType | PIT\_I |  | ShapeObject의 배경일 경우에만 의미 있는 아이템, 배경을 채우는 방식을 결정한다. (그림개체에는 해당사항 없음)0 \= 바둑판식으로1 \= 가로/위만 바둑판식으로 배열2 \= 가로/아래만 바둑판식으로 배열3 \= 세로/왼쪽만 바둑판식으로 배열4 \= 세로/오른쪽만 바둑판식으로 배열5 \= 크기에 맞추어6 \= 가운데로7 \= 가운데 위로8 \= 가운데 아래로9 \= 왼쪽 가운데로10 \= 왼쪽 위로11 \= 왼쪽 아래로12 \= 오른쪽 가운데로13 \= 오른쪽 위로14 \= 오른쪽 아래로 |
| SkipLeft | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 왼쪽 자르기 |
| SkipRight | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 오른쪽 자르기 |
| SkipTop | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 위 자르기 |
| SkipBottom | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 아래 자르기 |
| OriginalSizeX | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 원본 크기 X size |
| OriginalSizeY | PIT\_UI |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 원본 크기 Y size |
| InsideMarginLeft | PIT\_I4 |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 안쪽 여백. (왼쪽) |
| InsideMarginRight | PIT\_I4 |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 안쪽 여백. (오른쪽) |
| InsideMarginTop | PIT\_I4 |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 안쪽 여백. (위) |
| InsideMarginBottom | PIT\_I4 |  | 그림 개체일 경우에만 의미 있는 아이템, 이미지 안쪽 여백. (아래) |
| WindowsBrush | PIT\_UI1 |  | 현재 선택된 brush의 type이 면/무늬 브러시인가를 나타냄 |
| GradationBrush | PIT\_UI1 |  | 현재 선택된 brush의 type이 그러데이션 브러시인가를 나타냄 |
| ImageBrush | PIT\_UI1 |  | 현재 선택된 brush의 type이 그림 브러시인가를 나타냄 |
| ImageCreateOnDrag | PIT\_UI1 |  | 그림 개체 생성 시 마우스로 끌어 생성할지 여부(한글2007에 새로 추가) |

    """

    @property
    def file_name(self):
        """ShapeObject의 내용을 그림으로 표현할 경우 그림경로"""
        return self._pset.Item("FileName")

    @file_name.setter
    def file_name(self, value):
        if value is None:
            return self._pset.RemoveItem("FileName")
        assert isinstance(value, str), "값은 문자열이어야 합니다."
        return self._pset.SetItem("FileName", value)

    @property
    def embedded(self):
        """그림이 문서에 삽입(T)/링크(F)"""
        return self._pset.Item("Embedded")

    @embedded.setter
    def embedded(self, value):
        if value is None:
            return self._pset.RemoveItem("Embedded")
        assert value in [0, 1], "값은 0 (링크) 또는 1 (삽입)이어야 합니다."
        return self._pset.SetItem("Embedded", value)

    @property
    def pic_effect(self):
        """그림 효과 설정 (0: 없음, 1: 흑백, 2: 세피아 등)"""
        return self._pset.Item("PicEffect")

    @pic_effect.setter
    def pic_effect(self, value):
        if value is None:
            return self._pset.RemoveItem("PicEffect")
        assert value in range(3), "값은 0, 1 또는 2이어야 합니다."
        return self._pset.SetItem("PicEffect", value)

    @property
    def brightness(self):
        """밝기 조정 (-100 ~ 100)"""
        return self._pset.Item("Brightness")

    @brightness.setter
    def brightness(self, value):
        if value is None:
            return self._pset.RemoveItem("Brightness")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("Brightness", value)

    @property
    def contrast(self):
        """대비 조정 (-100 ~ 100)"""
        return self._pset.Item("Contrast")

    @contrast.setter
    def contrast(self, value):
        if value is None:
            return self._pset.RemoveItem("Contrast")
        assert -100 <= value <= 100, "값은 -100에서 100 사이여야 합니다."
        return self._pset.SetItem("Contrast", value)

    @property
    def reverse(self):
        """색 반전"""
        return self._pset.Item("Reverse")

    @reverse.setter
    def reverse(self, value):
        if value is None:
            return self._pset.RemoveItem("Reverse")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("Reverse", value)

    @property
    def draw_fill_image_type(self):
        """ShapeObject의 배경일 경우에만 의미 있는 아이템, 배경을 채우는 방식을 결정한다."""
        return self._pset.Item("DrawFillImageType")

    @draw_fill_image_type.setter
    def draw_fill_image_type(self, value):
        if value is None:
            return self._pset.RemoveItem("DrawFillImageType")
        assert 0 <= value <= 14, "값은 0에서 14 사이여야 합니다."
        return self._pset.SetItem("DrawFillImageType", value)

    @property
    def skip_left(self):
        """왼쪽 자르기"""
        return self._pset.Item("SkipLeft")

    @skip_left.setter
    def skip_left(self, value):
        if value is None:
            return self._pset.RemoveItem("SkipLeft")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("SkipLeft", value)

    @property
    def skip_right(self):
        """오른쪽 자르기"""
        return self._pset.Item("SkipRight")

    @skip_right.setter
    def skip_right(self, value):
        if value is None:
            return self._pset.RemoveItem("SkipRight")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("SkipRight", value)

    @property
    def skip_top(self):
        """위 자르기"""
        return self._pset.Item("SkipTop")

    @skip_top.setter
    def skip_top(self, value):
        if value is None:
            return self._pset.RemoveItem("SkipTop")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("SkipTop", value)

    @property
    def skip_bottom(self):
        """아래 자르기"""
        return self._pset.Item("SkipBottom")

    @skip_bottom.setter
    def skip_bottom(self, value):
        if value is None:
            return self._pset.RemoveItem("SkipBottom")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("SkipBottom", value)

    @property
    def original_size_x(self):
        """이미지 원본 크기 X size"""
        return self._pset.Item("OriginalSizeX")

    @original_size_x.setter
    def original_size_x(self, value):
        if value is None:
            return self._pset.RemoveItem("OriginalSizeX")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("OriginalSizeX", value)

    @property
    def original_size_y(self):
        """이미지 원본 크기 Y size"""
        return self._pset.Item("OriginalSizeY")

    @original_size_y.setter
    def original_size_y(self, value):
        if value is None:
            return self._pset.RemoveItem("OriginalSizeY")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("OriginalSizeY", value)

    @property
    def inside_margin_left(self):
        """이미지 안쪽 여백 (왼쪽)"""
        return self._pset.Item("InsideMarginLeft")

    @inside_margin_left.setter
    def inside_margin_left(self, value):
        if value is None:
            return self._pset.RemoveItem("InsideMarginLeft")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("InsideMarginLeft", value)

    @property
    def inside_margin_right(self):
        """이미지 안쪽 여백 (오른쪽)"""
        return self._pset.Item("InsideMarginRight")

    @inside_margin_right.setter
    def inside_margin_right(self, value):
        if value is None:
            return self._pset.RemoveItem("InsideMarginRight")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("InsideMarginRight", value)

    @property
    def inside_margin_top(self):
        """이미지 안쪽 여백 (위)"""
        return self._pset.Item("InsideMarginTop")

    @inside_margin_top.setter
    def inside_margin_top(self, value):
        if value is None:
            return self._pset.RemoveItem("InsideMarginTop")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("InsideMarginTop", value)

    @property
    def inside_margin_bottom(self):
        """이미지 안쪽 여백 (아래)"""
        return self._pset.Item("InsideMarginBottom")

    @inside_margin_bottom.setter
    def inside_margin_bottom(self, value):
        if value is None:
            return self._pset.RemoveItem("InsideMarginBottom")
        assert isinstance(value, int), "값은 정수여야 합니다."
        return self._pset.SetItem("InsideMarginBottom", value)

    @property
    def windows_brush(self):
        """현재 선택된 brush의 type이 면/무늬 브러시인가를 나타냄"""
        return self._pset.Item("WindowsBrush")

    @windows_brush.setter
    def windows_brush(self, value):
        if value is None:
            return self._pset.RemoveItem("WindowsBrush")
        assert value in [0, 1], "값은 0 (아님) 또는 1 (맞음)이어야 합니다."
        return self._pset.SetItem("WindowsBrush", value)

    @property
    def gradation_brush(self):
        """현재 선택된 brush의 type이 그러데이션 브러시인가를 나타냄"""
        return self._pset.Item("GradationBrush")

    @gradation_brush.setter
    def gradation_brush(self, value):
        if value is None:
            return self._pset.RemoveItem("GradationBrush")
        assert value in [0, 1], "값은 0 (아님) 또는 1 (맞음)이어야 합니다."
        return self._pset.SetItem("GradationBrush", value)

    @property
    def image_brush(self):
        """현재 선택된 brush의 type이 그림 브러시인가를 나타냄"""
        return self._pset.Item("ImageBrush")

    @image_brush.setter
    def image_brush(self, value):
        if value is None:
            return self._pset.RemoveItem("ImageBrush")
        assert value in [0, 1], "값은 0 (아님) 또는 1 (맞음)이어야 합니다."
        return self._pset.SetItem("ImageBrush", value)

    @property
    def image_create_on_drag(self):
        """그림 개체 생성 시 마우스로 끌어 생성할지 여부"""
        return self._pset.Item("ImageCreateOnDrag")

    @image_create_on_drag.setter
    def image_create_on_drag(self, value):
        if value is None:
            return self._pset.RemoveItem("ImageCreateOnDrag")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("ImageCreateOnDrag", value)


# %% ../nbs/02_api/02_parameters.ipynb 26
class ParaShape(ParameterSet):
    """
    ### ParaShape

91\) ParaShape : 문단 모양


| Item ID | Type | SubType | Description |
| --- | --- | --- | --- |
| LeftMargin | PIT\_I4 |  | 왼쪽 여백 (URC) |
| RightMargin | PIT\_I4 |  | 오른쪽 여백 (URC) |
| Indentation | PIT\_I4 |  | 들여쓰기/내어 쓰기 (URC) |
| PrevSpacing | PIT\_I4 |  | 문단 간격 위 (URC) |
| NextSpacing | PIT\_I4 |  | 문단 간격 아래 (URC) |
| LineSpacingType | PIT\_UI1 |  | 줄 간격 종류 (HWPUNIT)0 \= 글자에 따라1 \= 고정 값2 \= 여백만 지정 |
| LineSpacing | PIT\_I4 |  | 줄 간격 값. 줄 간격 종류(LineSpacingType)에 따라 :\- "글자에 따라"일 경우(0 \- 500%)\- “고정 값”일 경우(URC)\- “여백만 지정”일 경우(URC) |
| AlignType | PIT\_UI1 |  | 정렬 방식0 \= 양쪽 정렬1 \= 왼쪽 정렬2 \= 오른쪽 정렬3 \= 가운데 정렬4 \= 배분 정렬5 \= 나눔 정렬 (공백에만 배분) |
| BreakLatinWord | PIT\_UI1 |  | 줄 나눔 단위 (라틴 문자)0 \= 단어1 \= 하이픈2 \= 글자 |
| BreakNonLatinWord | PIT\_UI1 |  | 단위 (비 라틴 문자) TRUE \= 글자, FALSE \= 어절 |
| SnapToGrid | PIT\_UI1 |  | 편집 용지의 줄 격자 사용 (on / off) |
| Condense | PIT\_UI1 |  | 공백 최소값 (0 \- 75%) |
| WidowOrphan | PIT\_UI1 |  | 외톨이줄 보호 (on / off) |
| KeepWithNext | PIT\_UI1 |  | 다음 문단과 함께 (on / off) |
| KeepLinesTogether | PIT\_UI1 |  | 문단 보호 (on / off) |
| PagebreakBefore | PIT\_UI1 |  | 문단 앞에서 항상 쪽 나눔 (on / off) |
| TextAlignment | PIT\_UI1 |  | 세로 정렬0 \= 글꼴기준1 \= 위2 \= 가운데3 \= 아래 |
| FontLineHeight | PIT\_UI1 |  | 글꼴에 어울리는 줄 높이 (on / off) |
| HeadingType | PIT\_UI1 |  | 문단 머리 모양0 \= 없음1 \= 개요2 \= 번호3 \= 불릿 |
| Level | PIT\_UI1 |  | 단계 (0 \- 6\) |
| BorderConnect | PIT\_UI1 |  | 문단 테두리/배경 \- 테두리 연결 (on / off) |
| BorderText | PIT\_UI1 |  | 문단 테두리/배경 \- 여백 무시 (0 \= 단, 1 \= 텍스트) |
| BorderOffsetLeft | PIT\_I |  | 문단 테두리/배경 \- 4방향 간격 (HWPUNIT) : 왼쪽 |
| BorderOffsetRight | PIT\_I |  | 문단 테두리/배경 \- 4방향 간격 (HWPUNIT) : 오른쪽 |
| BorderOffsetTop | PIT\_I |  | 문단 테두리/배경 \- 4방향 간격 (HWPUNIT) : 위 |
| BorderOffsetBottom | PIT\_I |  | 문단 테두리/배경 \- 4방향 간격 (HWPUNIT) : 아래 |
| TailType | PIT\_UI1 |  | 문단 꼬리 모양 (마지막 꼬리 줄 적용) on/off |
| LineWrap | PIT\_UI1 |  | 글꼴에 어울리는 줄 높이 (on/off) |
| TabDef | PIT\_SET | TabDef | 탭 정의 |
| Numbering | PIT\_SET | NumberingShape | 문단 번호문단 머리 모양(HeadingType)이 ‘개요’, ‘번호’ 일 때 사용 |
| Bullet | PIT\_SET | BulletShape | 불릿 모양문단 머리 모양(HeadingType)이 ‘불릿’(글머리표) 일 때 사용 |
| BorderFill | PIT\_SET | BorderFill | 테두리/배경 |

 



    """

    @property
    def left_margin(self):
        """왼쪽 여백 (URC)"""
        return self._pset.Item("LeftMargin")

    @left_margin.setter
    def left_margin(self, value):
        if value is None:
            return self._pset.RemoveItem("LeftMargin")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("LeftMargin", value)

    @property
    def right_margin(self):
        """오른쪽 여백 (URC)"""
        return self._pset.Item("RightMargin")

    @right_margin.setter
    def right_margin(self, value):
        if value is None:
            return self._pset.RemoveItem("RightMargin")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("RightMargin", value)

    @property
    def indentation(self):
        """들여쓰기/내어쓰기 (URC)"""
        return self._pset.Item("Indentation")

    @indentation.setter
    def indentation(self, value):
        if value is None:
            return self._pset.RemoveItem("Indentation")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("Indentation", value)

    @property
    def prev_spacing(self):
        """문단 간격 위 (URC)"""
        return self._pset.Item("PrevSpacing")

    @prev_spacing.setter
    def prev_spacing(self, value):
        if value is None:
            return self._pset.RemoveItem("PrevSpacing")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("PrevSpacing", value)

    @property
    def next_spacing(self):
        """문단 간격 아래 (URC)"""
        return self._pset.Item("NextSpacing")

    @next_spacing.setter
    def next_spacing(self, value):
        if value is None:
            return self._pset.RemoveItem("NextSpacing")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("NextSpacing", value)

    @property
    def line_spacing_type(self):
        """줄 간격 종류:
        0 = 글자에 맞춤, 1 = 고정 값, 2 = 여백만 지정"""
        return self._pset.Item("LineSpacingType")

    @line_spacing_type.setter
    def line_spacing_type(self, value):
        if value is None:
            return self._pset.RemoveItem("LineSpacingType")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("LineSpacingType", value)

    @property
    def line_spacing(self):
        """줄 간격 (LineSpacingType에 따라 값 범위가 다름):
        - "글자에 맞춤": 0 - 500%
        - "고정 값": 정수 값 (URC)
        - "여백만 지정": 정수 값 (URC)
        """
        return self._pset.Item("LineSpacing")

    @line_spacing.setter
    def line_spacing(self, value):
        if value is None:
            return self._pset.RemoveItem("LineSpacing")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("LineSpacing", value)

    @property
    def align_type(self):
        """정렬 방식:
        0 = 왼쪽 정렬, 1 = 오른쪽 정렬, 2 = 가운데 정렬, 3 = 양쪽 정렬, 4 = 배분 정렬, 5 = 나눔 정렬
        """
        return self._pset.Item("AlignType")

    @align_type.setter
    def align_type(self, value):
        if value is None:
            return self._pset.RemoveItem("AlignType")
        assert value in [0, 1, 2, 3, 4, 5], "값은 0에서 5 사이여야 합니다."
        return self._pset.SetItem("AlignType", value)

    @property
    def break_latin_word(self):
        """줄 나눔 방식 (라틴 문자):
        0 = 끊지 않음, 1 = 하이픈, 2 = 글자 단위
        """
        return self._pset.Item("BreakLatinWord")

    @break_latin_word.setter
    def break_latin_word(self, value):
        if value is None:
            return self._pset.RemoveItem("BreakLatinWord")
        assert value in [0, 1, 2], "값은 0, 1, 2 중 하나여야 합니다."
        return self._pset.SetItem("BreakLatinWord", value)

    @property
    def break_non_latin_word(self):
        """줄 나눔 (비 라틴 문자): TRUE = 글자 단위, FALSE = 끊지 않음"""
        return self._pset.Item("BreakNonLatinWord")

    @break_non_latin_word.setter
    def break_non_latin_word(self, value):
        if value is None:
            return self._pset.RemoveItem("BreakNonLatinWord")
        assert value in [0, 1], "값은 0 (FALSE) 또는 1 (TRUE)이어야 합니다."
        return self._pset.SetItem("BreakNonLatinWord", value)

    @property
    def snap_to_grid(self):
        """문서 격자 사용 (on/off)"""
        return self._pset.Item("SnapToGrid")

    @snap_to_grid.setter
    def snap_to_grid(self, value):
        if value is None:
            return self._pset.RemoveItem("SnapToGrid")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("SnapToGrid", value)

    @property
    def condense(self):
        """공백 최소값 (0 - 75%)"""
        return self._pset.Item("Condense")

    @condense.setter
    def condense(self, value):
        if value is None:
            return self._pset.RemoveItem("Condense")
        assert 0 <= value <= 75, "값은 0에서 75 사이여야 합니다."
        return self._pset.SetItem("Condense", value)

    @property
    def widow_orphan(self):
        """외톨이줄 보호 (on / off)"""
        return self._pset.Item("WidowOrphan")

    @widow_orphan.setter
    def widow_orphan(self, value):
        if value is None:
            return self._pset.RemoveItem("WidowOrphan")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("WidowOrphan", value)

    @property
    def keep_with_next(self):
        """다음 문단과 함께 (on / off)"""
        return self._pset.Item("KeepWithNext")

    @keep_with_next.setter
    def keep_with_next(self, value):
        if value is None:
            return self._pset.RemoveItem("KeepWithNext")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("KeepWithNext", value)

    @property
    def keep_lines_together(self):
        """문단 보호 (on / off)"""
        return self._pset.Item("KeepLinesTogether")

    @keep_lines_together.setter
    def keep_lines_together(self, value):
        if value is None:
            return self._pset.RemoveItem("KeepLinesTogether")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("KeepLinesTogether", value)

    @property
    def pagebreak_before(self):
        """문단 앞에서 항상 쪽 나눔 (on / off)"""
        return self._pset.Item("PagebreakBefore")

    @pagebreak_before.setter
    def pagebreak_before(self, value):
        if value is None:
            return self._pset.RemoveItem("PagebreakBefore")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("PagebreakBefore", value)

    @property
    def text_alignment(self):
        """세로 정렬: 0 = 글꼴기준, 1 = 위, 2 = 가운데, 3 = 아래"""
        return self._pset.Item("TextAlignment")

    @text_alignment.setter
    def text_alignment(self, value):
        if value is None:
            return self._pset.RemoveItem("TextAlignment")
        assert value in [0, 1, 2, 3], "값은 0에서 3 사이여야 합니다."
        return self._pset.SetItem("TextAlignment", value)

    @property
    def font_line_height(self):
        """글꼴에 어울리는 줄 높이 (on / off)"""
        return self._pset.Item("FontLineHeight")

    @font_line_height.setter
    def font_line_height(self, value):
        if value is None:
            return self._pset.RemoveItem("FontLineHeight")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("FontLineHeight", value)

    @property
    def heading_type(self):
        """문단 머리 모양: 0 = 없음, 1 = 개요, 2 = 번호, 3 = 불릿"""
        return self._pset.Item("HeadingType")

    @heading_type.setter
    def heading_type(self, value):
        if value is None:
            return self._pset.RemoveItem("HeadingType")
        assert value in [0, 1, 2, 3], "값은 0에서 3 사이여야 합니다."
        return self._pset.SetItem("HeadingType", value)

    @property
    def level(self):
        """단계 (0 - 6)"""
        return self._pset.Item("Level")

    @level.setter
    def level(self, value):
        if value is None:
            return self._pset.RemoveItem("Level")
        assert 0 <= value <= 6, "값은 0에서 6 사이여야 합니다."
        return self._pset.SetItem("Level", value)

    @property
    def border_connect(self):
        """문단 테두리/배경 - 테두리 연결 (on / off)"""
        return self._pset.Item("BorderConnect")

    @border_connect.setter
    def border_connect(self, value):
        if value is None:
            return self._pset.RemoveItem("BorderConnect")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("BorderConnect", value)

    @property
    def border_text(self):
        """문단 테두리/배경 - 여백 무시: 0 = 단, 1 = 텍스트"""
        return self._pset.Item("BorderText")

    @border_text.setter
    def border_text(self, value):
        if value is None:
            return self._pset.RemoveItem("BorderText")
        assert value in [0, 1], "값은 0 또는 1이어야 합니다."
        return self._pset.SetItem("BorderText", value)

    @property
    def border_offset_left(self):
        """문단 테두리/배경 - 4방향 간격 (HWPUNIT): 왼쪽"""
        return self._pset.Item("BorderOffsetLeft")

    @border_offset_left.setter
    def border_offset_left(self, value):
        if value is None:
            return self._pset.RemoveItem("BorderOffsetLeft")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("BorderOffsetLeft", value)

    @property
    def border_offset_right(self):
        """문단 테두리/배경 - 4방향 간격 (HWPUNIT): 오른쪽"""
        return self._pset.Item("BorderOffsetRight")

    @border_offset_right.setter
    def border_offset_right(self, value):
        if value is None:
            return self._pset.RemoveItem("BorderOffsetRight")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("BorderOffsetRight", value)

    @property
    def border_offset_top(self):
        """문단 테두리/배경 - 4방향 간격 (HWPUNIT): 위"""
        return self._pset.Item("BorderOffsetTop")

    @border_offset_top.setter
    def border_offset_top(self, value):
        if value is None:
            return self._pset.RemoveItem("BorderOffsetTop")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("BorderOffsetTop", value)

    @property
    def border_offset_bottom(self):
        """문단 테두리/배경 - 4방향 간격 (HWPUNIT): 아래"""
        return self._pset.Item("BorderOffsetBottom")

    @border_offset_bottom.setter
    def border_offset_bottom(self, value):
        if value is None:
            return self._pset.RemoveItem("BorderOffsetBottom")
        assert isinstance(value, int), "값은 정수이어야 합니다."
        return self._pset.SetItem("BorderOffsetBottom", value)

    @property
    def tail_type(self):
        """문단 꼬리 모양 (마지막 꼬리 줄 적용) on/off"""
        return self._pset.Item("TailType")

    @tail_type.setter
    def tail_type(self, value):
        if value is None:
            return self._pset.RemoveItem("TailType")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("TailType", value)

    @property
    def line_wrap(self):
        """글꼴에 어울리는 줄 높이 (on/off)"""
        return self._pset.Item("LineWrap")

    @line_wrap.setter
    def line_wrap(self, value):
        if value is None:
            return self._pset.RemoveItem("LineWrap")
        assert value in [0, 1], "값은 0 (off) 또는 1 (on)이어야 합니다."
        return self._pset.SetItem("LineWrap", value)

    @property
    def tab_def(self):
        """탭 정의 (TabDef)"""
        return self._pset.Item("TabDef")

    @tab_def.setter
    def tab_def(self, value):
        if value is None:
            return self._pset.RemoveItem("TabDef")
        # Assuming TabDef is a specific object
        assert isinstance(value, TabDef), "값은 TabDef 객체이어야 합니다."
        return self._pset.SetItem("TabDef", value)

    @property
    def numbering(self):
        """문단 번호 (NumberingShape)"""
        return self._pset.Item("Numbering")

    @numbering.setter
    def numbering(self, value):
        if value is None:
            return self._pset.RemoveItem("Numbering")
        # Assuming NumberingShape is a specific object
        assert isinstance(value, NumberingShape), "값은 NumberingShape 객체이어야 합니다."
        return self._pset.SetItem("Numbering", value)

    @property
    def bullet(self):
        """불릿 모양 (BulletShape)"""
        return self._pset.Item("Bullet")

    @bullet.setter
    def bullet(self, value):
        if value is None:
            return self._pset.RemoveItem("Bullet")
        # Assuming BulletShape is a specific object
        assert isinstance(value, BulletShape), "값은 BulletShape 객체이어야 합니다."
        return self._pset.SetItem("Bullet", value)

    @property
    def border_fill(self):
        """테두리/배경 (BorderFill)"""
        return self._pset.Item("BorderFill")

    @border_fill.setter
    def border_fill(self, value):
        if value is None:
            return self._pset.RemoveItem("BorderFill")
        # Assuming BorderFill is a specific object
        assert isinstance(value, BorderFill), "값은 BorderFill 객체이어야 합니다."
        return self._pset.SetItem("BorderFill", value)
