# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_api/02_parameters.ipynb.

"""
Parameter value mappings for HWP parameter sets.
These mappings convert between human-readable strings and HWP numeric values.
"""

# Direction mappings
DIRECTION_MAP = {"left": 0, "right": 1, "top": 2, "bottom": 3}

# Size and alignment mappings
CAP_FULL_SIZE_MAP = {"exclude": 0, "include": 1}
ALIGNMENT_MAP = {"left": 0, "center": 1, "right": 2}
VERT_ALIGN_MAP = {"top": 0, "center": 1, "bottom": 2}
VERT_REL_TO_MAP = {"paper": 0, "page": 1, "paragraph": 2}
HORZ_REL_TO_MAP = {"paper": 0, "page": 1, "column": 2, "paragraph": 3}
HORZ_ALIGN_MAP = {"left": 0, "center": 1, "right": 2, "inside": 3, "outside": 4}
ALIGN_MAP = {"left": 0, "center": 1, "right": 2}
ALIGN_TYPE_MAP = {"between": 0, "left": 1, "right": 2, "center": 3, "ratio": 4, "shared": 5}

# Font and text mappings
FONTTYPE_MAP = {"don't care": 0, "TTF": 1, "HFT": 2, "dontcare": 0, "ttf": 1, "htf": 2}
TEXT_DIRECTION_MAP = {"horizontal": 0, "vertical": 1}
TEXT_ALIGN_MAP = {"font": 0, "up": 1, "middle": 2, "down": 3}
LINE_SPACING_TYPE_MAP = {"font": 0, "fixed": 1, "space": 2}

# Line and text wrapping mappings
LINE_WRAP_MAP = {"basic": 0, "no_newline": 1, "forced": 2}
TEXT_WRAP_MAP = {"square": 0, "top_bottom": 1, "behind": 2, "front": 3, "tight": 4, "through": 5}
TEXT_FLOW_MAP = {"both": 0, "left": 1, "right": 2, "largest": 3}
LATIN_LINE_BREAK_MAP = {"word": 0, "hyphen": 1, "letter": 2}
NONLATIN_LINE_BREAK_MAP = {"word": 0, "letter": 1}

# Style and effect mappings
SHADOW_TYPE_MAP = {"none": 0, "drop": 1, "continuous": 2}
BACKGROUND_TYPE_MAP = {"empty": 0, "fill": 1, "picture": 2, "gradation": 3}
GRADATION_TYPE_MAP = {"stripe": 1, "circle": 2, "cone": 3, "square": 4}
ROTATION_SETTING_MAP = {"none": 0, "setted_rotation": 1, "picture_centered_rotation": 2, "rotation_and_centered": 3}
PIC_EFFECT_MAP = {"none": 0, "bw": 1, "sepia": 2}

# Search and direction mappings
SEARCH_DIRECTION_MAP = {"down": 0, "up": 1, "doc": 2}

# Border and outline mappings
BORDER_TEXT_MAP = {"column": 0, "text": 1}
UNDERLINE_TYPE_MAP = {"none": 0, "bottom": 1, "center": 2, "top": 3}
OUTLINE_TYPE_MAP = {
    "none": 0, "solid": 1, "dot": 2, "thick": 3,
    "dash": 4, "dashdot": 5, "dashdotdot": 6,
}
STRIKEOUT_TYPE_MAP = {
    "none": 0, "red single": 1, "red double": 2,
    "text single": 3, "text double": 4,
}

# Special character and formatting mappings
USE_KERNING_MAP = {"off": 0, "on": 1}
DIAC_SYM_MARK_MAP = {"none": 0, "black circle": 1, "empty circle": 2}
USE_FONT_SPACE_MAP = {"off": 0, "on": 1}
HEADING_TYPE_MAP = {"none": 0, "outline": 1, "number": 2, "bullet": 3}

# Numbering and formatting mappings
NUMBERING_TYPE_MAP = {"none": 0, "picture": 1, "table": 2, "equation": 3}
NUMBER_FORMAT_MAP = {
    "1": 0, "circled 1": 1, "I": 2, "i": 3, "A": 4, "a": 5,
    "circled A": 6, "circled a": 7, "가": 8, "동그라미 가": 9,
    "ㄱ": 10, "동그라미 ㄱ": 11, "일": 12, "一": 13, "동그라미 一": 14
}

# Page and table mappings
PAGE_BREAK_MAP = {"none": 0, "cell": 1, "text": 2}

# All mappings registry for easy access
ALL_MAPPINGS = {
    "direction": DIRECTION_MAP,
    "cap_full_size": CAP_FULL_SIZE_MAP,
    "alignment": ALIGNMENT_MAP,
    "fonttype": FONTTYPE_MAP,
    "shadow_type": SHADOW_TYPE_MAP,
    "background_type": BACKGROUND_TYPE_MAP,
    "gradation_type": GRADATION_TYPE_MAP,
    "rotation_setting": ROTATION_SETTING_MAP,
    "search_direction": SEARCH_DIRECTION_MAP,
    "text_direction": TEXT_DIRECTION_MAP,
    "line_wrap": LINE_WRAP_MAP,
    "text_wrap": TEXT_WRAP_MAP,
    "text_flow": TEXT_FLOW_MAP,
    "vert_align": VERT_ALIGN_MAP,
    "vert_rel_to": VERT_REL_TO_MAP,
    "horz_rel_to": HORZ_REL_TO_MAP,
    "horz_align": HORZ_ALIGN_MAP,
    "align": ALIGN_MAP,
    "align_type": ALIGN_TYPE_MAP,
    "latin_line_break": LATIN_LINE_BREAK_MAP,
    "nonlatin_line_break": NONLATIN_LINE_BREAK_MAP,
    "text_align": TEXT_ALIGN_MAP,
    "heading_type": HEADING_TYPE_MAP,
    "border_text": BORDER_TEXT_MAP,
    "underline_type": UNDERLINE_TYPE_MAP,
    "outline_type": OUTLINE_TYPE_MAP,
    "strikeout_type": STRIKEOUT_TYPE_MAP,
    "use_kerning": USE_KERNING_MAP,
    "diac_sym_mark": DIAC_SYM_MARK_MAP,
    "use_font_space": USE_FONT_SPACE_MAP,
    "numbering_type": NUMBERING_TYPE_MAP,
    "number_format": NUMBER_FORMAT_MAP,
    "line_spacing_type": LINE_SPACING_TYPE_MAP,
    "pic_effect": PIC_EFFECT_MAP,
    "page_break": PAGE_BREAK_MAP,
}
